package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 16
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: cow
  target_upper: Cow
  target_all_caps: COW
  
  target_drops: cooked beef
  target_drops_plural: cooked beef
  
  target_slug: cow
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: cooked_beef
  
items:
  cooked_beef: minecraft:$target_drops_slug$