package:
  templates:
    - daily-template-lumber

variables:

  objective_amount: 16
  reward_amount: 2500
  
  world: Mining
  world_display: Mining

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: acacia logs
  target_upper: Acacia logs
  
  target_drops: acacia log
  target_drops_plural: acacia logs
  
  target_slug: acacia_log
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: acacia_log
  
items:
  acacia_log: minecraft:$target_drops_slug$