package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 16
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: sheep
  target_upper: Sheep
  target_all_caps: SHEEP
  
  target_drops: cooked mutton
  target_drops_plural: cooked mutton
  
  target_slug: sheep
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: cooked_mutton
  
items:
  cooked_mutton: minecraft:$target_drops_slug$