package:
  templates:
    - daily-base

objectives:
  collect: 'mobkill $target_all_caps$ $objective_amount$ conditions:worldCheck events:shrineStartFolder notify'
  shrine: 'chestput $shrineLocation$ $target_drops_slug$:$objective_amount$ events:finishFolder notify'

variables:
  type_upper: Mobkill
  type_lower: mobkill
  