package:
  templates:
    - daily-template-base

objectives:
  collect: 'fish $target_all_caps$ $objective_amount$ notify conditions:worldCheck events:shrineStartFolder'
  shrine: 'chestput $shrineLocation$ $target_drops_slug$:$objective_amount$ events:finishFolder notify'

variables:
  type_upper: Fishing
  type_lower: fishing
  