package:
  templates:
    - daily-template-lumber

variables:

  objective_amount: 16
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: cherry logs
  target_upper: Cherry logs
  
  target_drops: cherry log
  target_drops_plural: cherry logs
  
  target_slug: cherry_log
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: cherry_log
  
items:
  cherry_log: minecraft:$target_drops_slug$