package:
  templates:
  - daily

menus:
  levelMenu:
    height: 4
    title: Level Menu
    command: /levelfarming
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      "9": level1FarmingQuestsMenu
      "10": level2FarmingQuestsMenu
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1FarmingQuestsMenu:
        item: level1FarmingQuestsMenu
        text:
        - "&b[Level 1]"
        - "Farming Quests"
        click:
          left: openLevel1FarmingQuestsMenu
        close: true
      level2FarmingQuestsMenu:
        item: level1FarmingQuestsMenu
        text:
        - "&b[Level 2]"
        - "Farming Quests"
        click:
          left: openLevel2FarmingQuestsMenu
        close: true
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
events:
  openLevel1FarmingQuestsMenu: menu open daily-farming-level1.farmingQuestsMenu
  openLevel2FarmingQuestsMenu: menu open daily-farming-level2.farmingQuestsMenu

items:
  level1FarmingQuestsMenu: "IRON_HOE"
  level2FarmingQuestsMenu: "IRON_HOE"