package:
  templates:
  - daily-template

menus:
  levelMenu:
    height: 3
    title: Level Menu
    command: /levelfarming
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      "9": level1FarmingQuestsMenu
      "11": level2FarmingQuestsMenu
      19-26: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      18: "back"
    items:
      level1FarmingQuestsMenu:
        item: level1FarmingQuestsMenu
        text:
        - "&b[Level 1]"
        - "Farming Quests"
        click:
          left: openLevel1FarmingQuestsMenu
        close: true
      level2FarmingQuestsMenu:
        item: level2FarmingQuestsMenu
        text:
        - "&b[Level 2]"
        - "Farming Quests"
        click:
          left: openLevel2FarmingQuestsMenu
        close: true
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
events:
  openLevel1FarmingQuestsMenu: menu open daily-farming-level1.farmingQuestsMenu
  openLevel2FarmingQuestsMenu: menu open daily-farming-level2.farmingQuestsMenu

items:
  level1FarmingQuestsMenu: $level1GUIItem$
  level2FarmingQuestsMenu: $level2GUIItem$