package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 10
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: creepers
  target_upper: Creepers
  target_all_caps: CREEPER
  
  target_drops: gunpowder
  target_drops_plural: gunpowder
  
  target_slug: creeper
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: gunpowder
  
items:
  gunpowder: minecraft:$target_drops_slug$