package:
  templates:
  - daily-template
menus:
  questsMenu:
    height: 4
    title: Mobkill  Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: ChickenActiveFalse,ChickenActiveTrue,ChickenShrine,ChickenShrineFinished
      10: CowActiveFalse,CowActiveTrue,CowShrine,CowShrineFinished
      11: CreeperActiveFalse,CreeperActiveTrue,CreeperShrine,CreeperShrineFinished
      12: HuskActiveFalse,HuskActiveTrue,HuskShrine,HuskShrineFinished
      13: PigActiveFalse,PigActiveTrue,PigShrine,PigShrineFinished
      14: SheepActiveFalse,SheepActiveTrue,SheepShrine,SheepShrineFinished
      15: SkeletonActiveFalse,SkeletonActiveTrue,SkeletonShrine,SkeletonShrineFinished
      16: SpiderActiveFalse,SpiderActiveTrue,SpiderShrine,SpiderShrineFinished
      17: SquidActiveFalse,SquidActiveTrue,SquidShrine,SquidShrineFinished
      18: ZombieActiveFalse,ZombieActiveTrue,ZombieShrine,ZombieShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      ChickenActiveFalse:
        item: ChickenActiveFalse
        conditions: "!daily-mobkill-chicken.collectTaken"
        text:
          - $daily-mobkill-chicken.title$
          - $daily-mobkill-chicken.description_line_1$
          - $daily-mobkill-chicken.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-chicken.collectStartFolder
        close: true
      ChickenActiveTrue:
        item: ChickenActiveTrue
        conditions: daily-mobkill-chicken.collectTaken,!daily-mobkill-chicken.shrineTaken
        text:
          - $daily-mobkill-chicken.title$
          - $daily-mobkill-chicken.description_line_1$
          - $daily-mobkill-chicken.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-chicken.objective.collect.absoluteAmount%/%daily-mobkill-chicken.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-chicken.reset
        close: true
      ChickenShrine:
        item: ChickenActiveTrue
        conditions: daily-mobkill-chicken.shrineTaskActive
        text:
          - $daily-mobkill-chicken.title$
          - $daily-mobkill-chicken.shrine_line_1$
          - $daily-mobkill-chicken.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      ChickenShrineFinished:
        item: questComplete
        conditions: daily-mobkill-chicken.questComplete
        text:
          - $daily-mobkill-chicken.title$
          - $daily-mobkill-chicken.done_line_1$
          - $daily-mobkill-chicken.done_line_2$
          - 
          - $status.inProgress$
        close: false
      CowActiveFalse:
        item: CowActiveFalse
        conditions: "!daily-mobkill-cow.collectTaken"
        text:
          - $daily-mobkill-cow.title$
          - $daily-mobkill-cow.description_line_1$
          - $daily-mobkill-cow.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-cow.collectStartFolder
        close: true
      CowActiveTrue:
        item: CowActiveTrue
        conditions: daily-mobkill-cow.collectTaken,!daily-mobkill-cow.shrineTaken
        text:
          - $daily-mobkill-cow.title$
          - $daily-mobkill-cow.description_line_1$
          - $daily-mobkill-cow.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-cow.objective.collect.absoluteAmount%/%daily-mobkill-cow.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-cow.reset
        close: true
      CowShrine:
        item: CowActiveTrue
        conditions: daily-mobkill-cow.shrineTaskActive
        text:
          - $daily-mobkill-cow.title$
          - $daily-mobkill-cow.shrine_line_1$
          - $daily-mobkill-cow.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      CowShrineFinished:
        item: questComplete
        conditions: daily-mobkill-cow.questComplete
        text:
          - $daily-mobkill-cow.title$
          - $daily-mobkill-cow.done_line_1$
          - $daily-mobkill-cow.done_line_2$
          - 
          - $status.inProgress$
        close: false
      CreeperActiveFalse:
        item: CreeperActiveFalse
        conditions: "!daily-mobkill-creeper.collectTaken"
        text:
          - $daily-mobkill-creeper.title$
          - $daily-mobkill-creeper.description_line_1$
          - $daily-mobkill-creeper.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-creeper.collectStartFolder
        close: true
      CreeperActiveTrue:
        item: CreeperActiveTrue
        conditions: daily-mobkill-creeper.collectTaken,!daily-mobkill-creeper.shrineTaken
        text:
          - $daily-mobkill-creeper.title$
          - $daily-mobkill-creeper.description_line_1$
          - $daily-mobkill-creeper.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-creeper.objective.collect.absoluteAmount%/%daily-mobkill-creeper.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-creeper.reset
        close: true
      CreeperShrine:
        item: CreeperActiveTrue
        conditions: daily-mobkill-creeper.shrineTaskActive
        text:
          - $daily-mobkill-creeper.title$
          - $daily-mobkill-creeper.shrine_line_1$
          - $daily-mobkill-creeper.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      CreeperShrineFinished:
        item: questComplete
        conditions: daily-mobkill-creeper.questComplete
        text:
          - $daily-mobkill-creeper.title$
          - $daily-mobkill-creeper.done_line_1$
          - $daily-mobkill-creeper.done_line_2$
          - 
          - $status.inProgress$
        close: false
      HuskActiveFalse:
        item: HuskActiveFalse
        conditions: "!daily-mobkill-husk.collectTaken"
        text:
          - $daily-mobkill-husk.title$
          - $daily-mobkill-husk.description_line_1$
          - $daily-mobkill-husk.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-husk.collectStartFolder
        close: true
      HuskActiveTrue:
        item: HuskActiveTrue
        conditions: daily-mobkill-husk.collectTaken,!daily-mobkill-husk.shrineTaken
        text:
          - $daily-mobkill-husk.title$
          - $daily-mobkill-husk.description_line_1$
          - $daily-mobkill-husk.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-husk.objective.collect.absoluteAmount%/%daily-mobkill-husk.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-husk.reset
        close: true
      HuskShrine:
        item: HuskActiveTrue
        conditions: daily-mobkill-husk.shrineTaskActive
        text:
          - $daily-mobkill-husk.title$
          - $daily-mobkill-husk.shrine_line_1$
          - $daily-mobkill-husk.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      HuskShrineFinished:
        item: questComplete
        conditions: daily-mobkill-husk.questComplete
        text:
          - $daily-mobkill-husk.title$
          - $daily-mobkill-husk.done_line_1$
          - $daily-mobkill-husk.done_line_2$
          - 
          - $status.inProgress$
        close: false
      PigActiveFalse:
        item: PigActiveFalse
        conditions: "!daily-mobkill-pig.collectTaken"
        text:
          - $daily-mobkill-pig.title$
          - $daily-mobkill-pig.description_line_1$
          - $daily-mobkill-pig.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-pig.collectStartFolder
        close: true
      PigActiveTrue:
        item: PigActiveTrue
        conditions: daily-mobkill-pig.collectTaken,!daily-mobkill-pig.shrineTaken
        text:
          - $daily-mobkill-pig.title$
          - $daily-mobkill-pig.description_line_1$
          - $daily-mobkill-pig.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-pig.objective.collect.absoluteAmount%/%daily-mobkill-pig.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-pig.reset
        close: true
      PigShrine:
        item: PigActiveTrue
        conditions: daily-mobkill-pig.shrineTaskActive
        text:
          - $daily-mobkill-pig.title$
          - $daily-mobkill-pig.shrine_line_1$
          - $daily-mobkill-pig.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      PigShrineFinished:
        item: questComplete
        conditions: daily-mobkill-pig.questComplete
        text:
          - $daily-mobkill-pig.title$
          - $daily-mobkill-pig.done_line_1$
          - $daily-mobkill-pig.done_line_2$
          - 
          - $status.inProgress$
        close: false
      SheepActiveFalse:
        item: SheepActiveFalse
        conditions: "!daily-mobkill-sheep.collectTaken"
        text:
          - $daily-mobkill-sheep.title$
          - $daily-mobkill-sheep.description_line_1$
          - $daily-mobkill-sheep.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-sheep.collectStartFolder
        close: true
      SheepActiveTrue:
        item: SheepActiveTrue
        conditions: daily-mobkill-sheep.collectTaken,!daily-mobkill-sheep.shrineTaken
        text:
          - $daily-mobkill-sheep.title$
          - $daily-mobkill-sheep.description_line_1$
          - $daily-mobkill-sheep.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-sheep.objective.collect.absoluteAmount%/%daily-mobkill-sheep.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-sheep.reset
        close: true
      SheepShrine:
        item: SheepActiveTrue
        conditions: daily-mobkill-sheep.shrineTaskActive
        text:
          - $daily-mobkill-sheep.title$
          - $daily-mobkill-sheep.shrine_line_1$
          - $daily-mobkill-sheep.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      SheepShrineFinished:
        item: questComplete
        conditions: daily-mobkill-sheep.questComplete
        text:
          - $daily-mobkill-sheep.title$
          - $daily-mobkill-sheep.done_line_1$
          - $daily-mobkill-sheep.done_line_2$
          - 
          - $status.inProgress$
        close: false
      SkeletonActiveFalse:
        item: SkeletonActiveFalse
        conditions: "!daily-mobkill-skeleton.collectTaken"
        text:
          - $daily-mobkill-skeleton.title$
          - $daily-mobkill-skeleton.description_line_1$
          - $daily-mobkill-skeleton.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-skeleton.collectStartFolder
        close: true
      SkeletonActiveTrue:
        item: SkeletonActiveTrue
        conditions: daily-mobkill-skeleton.collectTaken,!daily-mobkill-skeleton.shrineTaken
        text:
          - $daily-mobkill-skeleton.title$
          - $daily-mobkill-skeleton.description_line_1$
          - $daily-mobkill-skeleton.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-skeleton.objective.collect.absoluteAmount%/%daily-mobkill-skeleton.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-skeleton.reset
        close: true
      SkeletonShrine:
        item: SkeletonActiveTrue
        conditions: daily-mobkill-skeleton.shrineTaskActive
        text:
          - $daily-mobkill-skeleton.title$
          - $daily-mobkill-skeleton.shrine_line_1$
          - $daily-mobkill-skeleton.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      SkeletonShrineFinished:
        item: questComplete
        conditions: daily-mobkill-skeleton.questComplete
        text:
          - $daily-mobkill-skeleton.title$
          - $daily-mobkill-skeleton.done_line_1$
          - $daily-mobkill-skeleton.done_line_2$
          - 
          - $status.inProgress$
        close: false
      SpiderActiveFalse:
        item: SpiderActiveFalse
        conditions: "!daily-mobkill-spider.collectTaken"
        text:
          - $daily-mobkill-spider.title$
          - $daily-mobkill-spider.description_line_1$
          - $daily-mobkill-spider.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-spider.collectStartFolder
        close: true
      SpiderActiveTrue:
        item: SpiderActiveTrue
        conditions: daily-mobkill-spider.collectTaken,!daily-mobkill-spider.shrineTaken
        text:
          - $daily-mobkill-spider.title$
          - $daily-mobkill-spider.description_line_1$
          - $daily-mobkill-spider.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-spider.objective.collect.absoluteAmount%/%daily-mobkill-spider.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-spider.reset
        close: true
      SpiderShrine:
        item: SpiderActiveTrue
        conditions: daily-mobkill-spider.shrineTaskActive
        text:
          - $daily-mobkill-spider.title$
          - $daily-mobkill-spider.shrine_line_1$
          - $daily-mobkill-spider.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      SpiderShrineFinished:
        item: questComplete
        conditions: daily-mobkill-spider.questComplete
        text:
          - $daily-mobkill-spider.title$
          - $daily-mobkill-spider.done_line_1$
          - $daily-mobkill-spider.done_line_2$
          - 
          - $status.inProgress$
        close: false
      SquidActiveFalse:
        item: SquidActiveFalse
        conditions: "!daily-mobkill-squid.collectTaken"
        text:
          - $daily-mobkill-squid.title$
          - $daily-mobkill-squid.description_line_1$
          - $daily-mobkill-squid.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-squid.collectStartFolder
        close: true
      SquidActiveTrue:
        item: SquidActiveTrue
        conditions: daily-mobkill-squid.collectTaken,!daily-mobkill-squid.shrineTaken
        text:
          - $daily-mobkill-squid.title$
          - $daily-mobkill-squid.description_line_1$
          - $daily-mobkill-squid.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-squid.objective.collect.absoluteAmount%/%daily-mobkill-squid.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-squid.reset
        close: true
      SquidShrine:
        item: SquidActiveTrue
        conditions: daily-mobkill-squid.shrineTaskActive
        text:
          - $daily-mobkill-squid.title$
          - $daily-mobkill-squid.shrine_line_1$
          - $daily-mobkill-squid.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      SquidShrineFinished:
        item: questComplete
        conditions: daily-mobkill-squid.questComplete
        text:
          - $daily-mobkill-squid.title$
          - $daily-mobkill-squid.done_line_1$
          - $daily-mobkill-squid.done_line_2$
          - 
          - $status.inProgress$
        close: false
      ZombieActiveFalse:
        item: ZombieActiveFalse
        conditions: "!daily-mobkill-zombie.collectTaken"
        text:
          - $daily-mobkill-zombie.title$
          - $daily-mobkill-zombie.description_line_1$
          - $daily-mobkill-zombie.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-mobkill-zombie.collectStartFolder
        close: true
      ZombieActiveTrue:
        item: ZombieActiveTrue
        conditions: daily-mobkill-zombie.collectTaken,!daily-mobkill-zombie.shrineTaken
        text:
          - $daily-mobkill-zombie.title$
          - $daily-mobkill-zombie.description_line_1$
          - $daily-mobkill-zombie.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mobkill-zombie.objective.collect.absoluteAmount%/%daily-mobkill-zombie.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mobkill-zombie.reset
        close: true
      ZombieShrine:
        item: ZombieActiveTrue
        conditions: daily-mobkill-zombie.shrineTaskActive
        text:
          - $daily-mobkill-zombie.title$
          - $daily-mobkill-zombie.shrine_line_1$
          - $daily-mobkill-zombie.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      ZombieShrineFinished:
        item: questComplete
        conditions: daily-mobkill-zombie.questComplete
        text:
          - $daily-mobkill-zombie.title$
          - $daily-mobkill-zombie.done_line_1$
          - $daily-mobkill-zombie.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
items:
  ChickenActiveFalse: $daily-mobkill-chicken.target_drops_slug$
  ChickenActiveTrue: $daily-mobkill-chicken.target_drops_slug$ $enchants$ $flags$
  CowActiveFalse: $daily-mobkill-cow.target_drops_slug$
  CowActiveTrue: $daily-mobkill-cow.target_drops_slug$ $enchants$ $flags$
  CreeperActiveFalse: $daily-mobkill-creeper.target_drops_slug$
  CreeperActiveTrue: $daily-mobkill-creeper.target_drops_slug$ $enchants$ $flags$
  HuskActiveFalse: $daily-mobkill-husk.target_drops_slug$
  HuskActiveTrue: $daily-mobkill-husk.target_drops_slug$ $enchants$ $flags$
  PigActiveFalse: $daily-mobkill-pig.target_drops_slug$
  PigActiveTrue: $daily-mobkill-pig.target_drops_slug$ $enchants$ $flags$
  SheepActiveFalse: $daily-mobkill-sheep.target_drops_slug$
  SheepActiveTrue: $daily-mobkill-sheep.target_drops_slug$ $enchants$ $flags$
  SkeletonActiveFalse: $daily-mobkill-skeleton.target_drops_slug$
  SkeletonActiveTrue: $daily-mobkill-skeleton.target_drops_slug$ $enchants$ $flags$
  SpiderActiveFalse: $daily-mobkill-spider.target_drops_slug$
  SpiderActiveTrue: $daily-mobkill-spider.target_drops_slug$ $enchants$ $flags$
  SquidActiveFalse: $daily-mobkill-squid.target_drops_slug$
  SquidActiveTrue: $daily-mobkill-squid.target_drops_slug$ $enchants$ $flags$
  ZombieActiveFalse: $daily-mobkill-zombie.target_drops_slug$
  ZombieActiveTrue: $daily-mobkill-zombie.target_drops_slug$ $enchants$ $flags$
