package:
  templates:
    - daily-template

menus:
  levelMenu:
    height: 4
    title: Level Menu
    command: /levelmobkill
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      "9": level1MobkillQuestsMenu
      "10": level2MobkillQuestsMenu
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1MobkillQuestsMenu:
        item: level1MobkillQuestsMenu
        text:
        - "&b[Level 1]"
        - "Mobkill Quests"
        click:
          left: openLevel1MobkillQuestsMenu
        close: true
      level2MobkillQuestsMenu:
        item: level2MobkillQuestsMenu
        text:
        - "&b[Level 2]"
        - "Mobkill Quests"
        click:
          left: openLevel2MobkillQuestsMenu
        close: true
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
events:
  openLevel1MobkillQuestsMenu: menu open daily-mobkill-level1.mobkillQuestsMenu
  openLevel2MobkillQuestsMenu: menu open daily-mobkill-level2.mobkillQuestsMenu

items:
  level1MobkillQuestsMenu: $level1GUIItem$
  level2MobkillQuestsMenu: $level2GUIItem$