package:
  templates:
    - daily

menus:
  mobkillingQuestsMenu:
    height: 4
    title: "Mobkill Quests"
    slots:
      0-3: "filler,filler,filler,filler"
      4: "reputation"
      5-8: "filler,filler,filler,filler"
      9: "tier1ZombieNotStarted,tier1ZombieActive,tier1ZombieShrine,tier1ZombieDone"
      10: "tier1CreeperNotStarted,tier1CreeperActive,tier1CreeperShrine,tier1CreeperDone"
      11: "tier1SkeletonNotStarted,tier1SkeletonActive,tier1SkeletonShrine,tier1SkeletonDone"
      12: "tier1PigNotStarted,tier1PigActive,tier1PigShrine,tier1PigDone"
      13: "tier1SpiderNotStarted,tier1SpiderActive,tier1SpiderShrine,tier1SpiderDone"
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
    ##################
    ## ZOMBIE HUNT  ##
    ##################
      tier1ZombieNotStarted:
        item: "tier1ZombieNotStarted"
        conditions: "!daily-mobkill-tier1-zombie.collectTaken"
        text:
          - '$daily-mobkill-tier1-zombie.title$'
          - '$daily-mobkill-tier1-zombie.description_line_1$'
          - '$daily-mobkill-tier1-zombie.description_line_2$'
          - ""
          - $status.notStarted$
          - $action.start$
        click:
          left: "daily.mobkillCheckActive,daily-mobkill-tier1-zombie.collectStartFolder"
        close: true
      tier1ZombieActive:
        item: "tier1ZombieActive"
        conditions: "daily-mobkill-tier1-zombie.collectTaken,!daily-mobkill-tier1-zombie.shrineTaken"
        text:
          - '$daily-mobkill-tier1-zombie.title$'
          - '$daily-mobkill-tier1-zombie.description_line_1$'
          - '$daily-mobkill-tier1-zombie.description_line_2$'
          - ""
          - $status.inProgress$
          - "%daily-mobkill-tier1-zombie.objective.collect.absoluteAmount%/%daily-mobkill-tier1-zombie.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: "resetNotify,daily-mobkill-tier1-zombie.reset"
      tier1ZombieShrine:
        item: "tier1ZombieActive"
        conditions: "daily-mobkill-tier1-zombie.shrineTaskActive"
        text:
          - '$daily-mobkill-tier1-zombie.title$'
          - '$daily-mobkill-tier1-zombie.shrine_line_1$'
          - '$daily-mobkill-tier1-zombie.shrine_line_2$'
          - ""
          - $status.inProgress$
        close: false
      tier1ZombieDone:
        item: "questComplete"
        conditions: "daily-mobkill-tier1-zombie.questComplete"
        text:
          - '$daily-mobkill-tier1-zombie.title$'
          - '$daily-mobkill-tier1-zombie.done_line_1$'
          - '$daily-mobkill-tier1-zombie.done_line_2$'
          - ""
          - $status.complete$
        close: false
    ##################
    ## Creepy Story ##
    ##################
      tier1CreeperNotStarted:
        item: "tier1CreeperNotStarted"
        conditions: "!daily-mobkill-tier1-creeper.collectTaken"
        text:
          - '$daily-mobkill-tier1-creeper.title$'
          - '$daily-mobkill-tier1-creeper.description_line_1$'
          - '$daily-mobkill-tier1-creeper.description_line_2$'
          - ""
          - $status.notStarted$
          - $action.start$
        click:
          left: "daily.mobkillCheckActive,daily-mobkill-tier1-creeper.collectStartFolder"
        close: true
      tier1CreeperActive:
        item: "tier1CreeperActive"
        conditions: "daily-mobkill-tier1-creeper.collectTaken,!daily-mobkill-tier1-creeper.shrineTaken"
        text:
          - '$daily-mobkill-tier1-creeper.title$'
          - '$daily-mobkill-tier1-creeper.description_line_1$'
          - '$daily-mobkill-tier1-creeper.description_line_2$'
          - ""
          - $status.inProgress$
          - "%daily-mobkill-tier1-creeper.objective.collect.absoluteAmount%/%daily-mobkill-tier1-creeper.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: "resetNotify,daily-mobkill-tier1-creeper.reset"
      tier1CreeperShrine:
        item: "tier1CreeperActive"
        conditions: "daily-mobkill-tier1-creeper.shrineTaskActive"
        text:
          - '$daily-mobkill-tier1-creeper.title$'
          - '$daily-mobkill-tier1-creeper.shrine_line_1$'
          - '$daily-mobkill-tier1-creeper.shrine_line_2$'
          - ""
          - $status.inProgress$
        close: false
      tier1CreeperDone:
        item: "questComplete"
        conditions: "daily-mobkill-tier1-creeper.questComplete"
        text:
          - '$daily-mobkill-tier1-creeper.title$'
          - '$daily-mobkill-tier1-creeper.done_line_1$'
          - '$daily-mobkill-tier1-creeper.done_line_2$'
          - ""
          - $status.complete$
        close: false
    ##############
    ## SKELETON ##
    ##############
      tier1SkeletonNotStarted:
        item: "tier1SkeletonNotStarted"
        conditions: "!daily-mobkill-tier1-skeleton.collectTaken"
        text:
          - '$daily-mobkill-tier1-skeleton.title$'
          - '$daily-mobkill-tier1-skeleton.description_line_1$'
          - '$daily-mobkill-tier1-skeleton.description_line_2$'
          - ""
          - $status.notStarted$
          - $action.start$
        click:
          left: "daily.mobkillCheckActive,daily-mobkill-tier1-skeleton.collectStartFolder"
        close: true
      tier1SkeletonActive:
        item: "tier1SkeletonActive"
        conditions: "daily-mobkill-tier1-skeleton.collectTaken,!daily-mobkill-tier1-skeleton.shrineTaken"
        text:
          - '$daily-mobkill-tier1-skeleton.title$'
          - '$daily-mobkill-tier1-skeleton.description_line_1$'
          - '$daily-mobkill-tier1-skeleton.description_line_2$'
          - ""
          - $status.inProgress$
          - "%daily-mobkill-tier1-skeleton.objective.collect.absoluteAmount%/%daily-mobkill-tier1-skeleton.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: "resetNotify,daily-mobkill-tier1-skeleton.reset"
      tier1SkeletonShrine:
        item: "tier1SkeletonActive"
        conditions: "daily-mobkill-tier1-skeleton.shrineTaskActive"
        text:
          - '$daily-mobkill-tier1-skeleton.title$'
          - '$daily-mobkill-tier1-skeleton.shrine_line_1$'
          - '$daily-mobkill-tier1-skeleton.shrine_line_2$'
          - ""
          - $status.inProgress$
        close: false
      tier1SkeletonDone:
        item: "questComplete"
        conditions: "daily-mobkill-tier1-skeleton.questComplete"
        text:
          - '$daily-mobkill-tier1-skeleton.title$'
          - '$daily-mobkill-tier1-skeleton.done_line_1$'
          - '$daily-mobkill-tier1-skeleton.done_line_2$'
          - ""
          - $status.complete$
        close: false
    #########
    ## PIG ##
    #########
      tier1PigNotStarted:
        item: "tier1PigNotStarted"
        conditions: "!daily-mobkill-tier1-pig.collectTaken"
        text:
          - '$daily-mobkill-tier1-pig.title$'
          - '$daily-mobkill-tier1-pig.description_line_1$'
          - '$daily-mobkill-tier1-pig.description_line_2$'
          - ""
          - $status.notStarted$
          - $action.start$
        click:
          left: "daily.mobkillCheckActive,daily-mobkill-tier1-pig.collectStartFolder"
        close: true
      tier1PigActive:
        item: "tier1PigActive"
        conditions: "daily-mobkill-tier1-pig.collectTaken,!daily-mobkill-tier1-pig.shrineTaken"
        text:
          - '$daily-mobkill-tier1-pig.title$'
          - '$daily-mobkill-tier1-pig.description_line_1$'
          - '$daily-mobkill-tier1-pig.description_line_2$'
          - ""
          - $status.inProgress$
          - "%daily-mobkill-tier1-pig.objective.collect.absoluteAmount%/%daily-mobkill-tier1-pig.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: "resetNotify,daily-mobkill-tier1-pig.reset"
      tier1PigShrine:
        item: "tier1PigActive"
        conditions: "daily-mobkill-tier1-pig.shrineTaskActive"
        text:
          - '$daily-mobkill-tier1-pig.title$'
          - '$daily-mobkill-tier1-pig.shrine_line_1$'
          - '$daily-mobkill-tier1-pig.shrine_line_2$'
          - ""
          - $status.inProgress$
        close: false
      tier1PigDone:
        item: "questComplete"
        conditions: "daily-mobkill-tier1-pig.questComplete"
        text:
          - '$daily-mobkill-tier1-pig.title$'
          - '$daily-mobkill-tier1-pig.done_line_1$'
          - '$daily-mobkill-tier1-pig.done_line_2$'
          - ""
          - $status.complete$
        close: false
    ############
    ## SPIDER ##
    ############
      tier1SpiderNotStarted:
        item: "tier1SpiderNotStarted"
        conditions: "!daily-mobkill-tier1-spider.collectTaken"
        text:
          - '$daily-mobkill-tier1-spider.title$'
          - '$daily-mobkill-tier1-spider.description_line_1$'
          - '$daily-mobkill-tier1-spider.description_line_2$'
          - ""
          - $status.notStarted$
          - $action.start$
        click:
          left: "daily.mobkillCheckActive,daily-mobkill-tier1-spider.collectStartFolder"
        close: true
      tier1SpiderActive:
        item: "tier1SpiderActive"
        conditions: "daily-mobkill-tier1-spider.collectTaken,!daily-mobkill-tier1-spider.shrineTaken"
        text:
          - '$daily-mobkill-tier1-spider.title$'
          - '$daily-mobkill-tier1-spider.description_line_1$'
          - '$daily-mobkill-tier1-spider.description_line_2$'
          - ""
          - $status.inProgress$
          - "%daily-mobkill-tier1-spider.objective.collect.absoluteAmount%/%daily-mobkill-tier1-spider.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: "resetNotify,daily-mobkill-tier1-spider.reset"
      tier1SpiderShrine:
        item: "tier1SpiderActive"
        conditions: "daily-mobkill-tier1-spider.shrineTaskActive"
        text:
          - '$daily-mobkill-tier1-spider.title$'
          - '$daily-mobkill-tier1-spider.shrine_line_1$'
          - '$daily-mobkill-tier1-spider.shrine_line_2$'
          - ""
          - $status.inProgress$
        close: false
      tier1SpiderDone:
        item: "questComplete"
        conditions: "daily-mobkill-tier1-spider.questComplete"
        text:
          - '$daily-mobkill-tier1-spider.title$'
          - '$daily-mobkill-tier1-spider.done_line_1$'
          - '$daily-mobkill-tier1-spider.done_line_2$'
          - ""
          - $status.complete$
        close: false
    #################
    ## UI ELEMENTS ##
    #################
      filler: 
        text: "&a "
        item: "filler"
      back:
        item: "back"
        amount: 1
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
items:
  tier1ZombieNotStarted: "$daily-mobkill-tier1-zombie.target_drops_slug$"
  tier1ZombieActive: "$daily-mobkill-tier1-zombie.target_drops_slug$ $enchants$ $flags$"
  tier1CreeperNotStarted: "$daily-mobkill-tier1-creeper.target_drops_slug$"
  tier1CreeperActive: "$daily-mobkill-tier1-creeper.target_drops_slug$ $enchants$ $flags$"
  tier1PigNotStarted: "$daily-mobkill-tier1-pig.target_drops_slug$"
  tier1PigActive: "$daily-mobkill-tier1-pig.target_drops_slug$ $enchants$ $flags$"
  tier1SkeletonNotStarted: "$daily-mobkill-tier1-skeleton.target_drops_slug$"
  tier1SkeletonActive: "$daily-mobkill-tier1-skeleton.target_drops_slug$ $enchants$ $flags$"
  tier1SpiderNotStarted: "$daily-mobkill-tier1-spider.target_drops_slug$"
  tier1SpiderActive: "$daily-mobkill-tier1-spider.target_drops_slug$ $enchants$ $flags$"