package:
  templates:
    - daily-lumber

variables:

  objective_amount: 16
  reward_amount: 2750
  
  world: Mining
  world_display: Mining

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: oak logs
  target_upper: Oak logs
  
  target_drops: oak log
  target_drops_plural: oak logs
  
  target_slug: oak_log
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: oak_log
  
items:
  oak_log: minecraft:$target_drops_slug$