package:
  templates:
  - daily-template
menus:
  farmingQuestsMenu:
    height: 4
    title: Farming level2 Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level2BambooActiveFalse,level2BambooActiveTrue,level2BambooShrine,level2BambooShrineFinished
      10: level2CactusActiveFalse,level2CactusActiveTrue,level2CactusShrine,level2CactusShrineFinished
      11: level2MelonActiveFalse,level2MelonActiveTrue,level2MelonShrine,level2MelonShrineFinished
      12: level2PumpkinActiveFalse,level2PumpkinActiveTrue,level2PumpkinShrine,level2PumpkinShrineFinished
      13: level2SweetberryActiveFalse,level2SweetberryActiveTrue,level2SweetberryShrine,level2SweetberryShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level2BambooActiveFalse:
        item: level2BambooActiveFalse
        conditions: "!daily-farming-level2-bamboo.collectTaken"
        text:
          - $daily-farming-level2-bamboo.title$
          - $daily-farming-level2-bamboo.description_line_1$
          - $daily-farming-level2-bamboo.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level2-bamboo.collectStartFolder
        close: true
      level2BambooActiveTrue:
        item: level2BambooActiveTrue
        conditions: daily-farming-level2-bamboo.collectTaken,!daily-farming-level2-bamboo.shrineTaken
        text:
          - $daily-farming-level2-bamboo.title$
          - $daily-farming-level2-bamboo.description_line_1$
          - $daily-farming-level2-bamboo.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level2-bamboo.objective.collect.absoluteAmount%/%daily-farming-level2-bamboo.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level2-bamboo.reset
        close: true
      level2BambooShrine:
        item: level2BambooActiveTrue
        conditions: daily-farming-level2-bamboo.shrineTaskActive
        text:
          - $daily-farming-level2-bamboo.title$
          - $daily-farming-level2-bamboo.shrine_line_1$
          - $daily-farming-level2-bamboo.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2BambooShrineFinished:
        item: questComplete
        conditions: daily-farming-level2-bamboo.questComplete
        text:
          - $daily-farming-level2-bamboo.title$
          - $daily-farming-level2-bamboo.done_line_1$
          - $daily-farming-level2-bamboo.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2CactusActiveFalse:
        item: level2CactusActiveFalse
        conditions: "!daily-farming-level2-cactus.collectTaken"
        text:
          - $daily-farming-level2-cactus.title$
          - $daily-farming-level2-cactus.description_line_1$
          - $daily-farming-level2-cactus.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level2-cactus.collectStartFolder
        close: true
      level2CactusActiveTrue:
        item: level2CactusActiveTrue
        conditions: daily-farming-level2-cactus.collectTaken,!daily-farming-level2-cactus.shrineTaken
        text:
          - $daily-farming-level2-cactus.title$
          - $daily-farming-level2-cactus.description_line_1$
          - $daily-farming-level2-cactus.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level2-cactus.objective.collect.absoluteAmount%/%daily-farming-level2-cactus.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level2-cactus.reset
        close: true
      level2CactusShrine:
        item: level2CactusActiveTrue
        conditions: daily-farming-level2-cactus.shrineTaskActive
        text:
          - $daily-farming-level2-cactus.title$
          - $daily-farming-level2-cactus.shrine_line_1$
          - $daily-farming-level2-cactus.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2CactusShrineFinished:
        item: questComplete
        conditions: daily-farming-level2-cactus.questComplete
        text:
          - $daily-farming-level2-cactus.title$
          - $daily-farming-level2-cactus.done_line_1$
          - $daily-farming-level2-cactus.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2MelonActiveFalse:
        item: level2MelonActiveFalse
        conditions: "!daily-farming-level2-melon.collectTaken"
        text:
          - $daily-farming-level2-melon.title$
          - $daily-farming-level2-melon.description_line_1$
          - $daily-farming-level2-melon.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level2-melon.collectStartFolder
        close: true
      level2MelonActiveTrue:
        item: level2MelonActiveTrue
        conditions: daily-farming-level2-melon.collectTaken,!daily-farming-level2-melon.shrineTaken
        text:
          - $daily-farming-level2-melon.title$
          - $daily-farming-level2-melon.description_line_1$
          - $daily-farming-level2-melon.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level2-melon.objective.collect.absoluteAmount%/%daily-farming-level2-melon.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level2-melon.reset
        close: true
      level2MelonShrine:
        item: level2MelonActiveTrue
        conditions: daily-farming-level2-melon.shrineTaskActive
        text:
          - $daily-farming-level2-melon.title$
          - $daily-farming-level2-melon.shrine_line_1$
          - $daily-farming-level2-melon.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2MelonShrineFinished:
        item: questComplete
        conditions: daily-farming-level2-melon.questComplete
        text:
          - $daily-farming-level2-melon.title$
          - $daily-farming-level2-melon.done_line_1$
          - $daily-farming-level2-melon.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2PumpkinActiveFalse:
        item: level2PumpkinActiveFalse
        conditions: "!daily-farming-level2-pumpkin.collectTaken"
        text:
          - $daily-farming-level2-pumpkin.title$
          - $daily-farming-level2-pumpkin.description_line_1$
          - $daily-farming-level2-pumpkin.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level2-pumpkin.collectStartFolder
        close: true
      level2PumpkinActiveTrue:
        item: level2PumpkinActiveTrue
        conditions: daily-farming-level2-pumpkin.collectTaken,!daily-farming-level2-pumpkin.shrineTaken
        text:
          - $daily-farming-level2-pumpkin.title$
          - $daily-farming-level2-pumpkin.description_line_1$
          - $daily-farming-level2-pumpkin.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level2-pumpkin.objective.collect.absoluteAmount%/%daily-farming-level2-pumpkin.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level2-pumpkin.reset
        close: true
      level2PumpkinShrine:
        item: level2PumpkinActiveTrue
        conditions: daily-farming-level2-pumpkin.shrineTaskActive
        text:
          - $daily-farming-level2-pumpkin.title$
          - $daily-farming-level2-pumpkin.shrine_line_1$
          - $daily-farming-level2-pumpkin.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2PumpkinShrineFinished:
        item: questComplete
        conditions: daily-farming-level2-pumpkin.questComplete
        text:
          - $daily-farming-level2-pumpkin.title$
          - $daily-farming-level2-pumpkin.done_line_1$
          - $daily-farming-level2-pumpkin.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2SweetberryActiveFalse:
        item: level2SweetberryActiveFalse
        conditions: "!daily-farming-level2-sweetberry.collectTaken"
        text:
          - $daily-farming-level2-sweetberry.title$
          - $daily-farming-level2-sweetberry.description_line_1$
          - $daily-farming-level2-sweetberry.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level2-sweetberry.collectStartFolder
        close: true
      level2SweetberryActiveTrue:
        item: level2SweetberryActiveTrue
        conditions: daily-farming-level2-sweetberry.collectTaken,!daily-farming-level2-sweetberry.shrineTaken
        text:
          - $daily-farming-level2-sweetberry.title$
          - $daily-farming-level2-sweetberry.description_line_1$
          - $daily-farming-level2-sweetberry.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level2-sweetberry.objective.collect.absoluteAmount%/%daily-farming-level2-sweetberry.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level2-sweetberry.reset
        close: true
      level2SweetberryShrine:
        item: level2SweetberryActiveTrue
        conditions: daily-farming-level2-sweetberry.shrineTaskActive
        text:
          - $daily-farming-level2-sweetberry.title$
          - $daily-farming-level2-sweetberry.shrine_line_1$
          - $daily-farming-level2-sweetberry.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2SweetberryShrineFinished:
        item: questComplete
        conditions: daily-farming-level2-sweetberry.questComplete
        text:
          - $daily-farming-level2-sweetberry.title$
          - $daily-farming-level2-sweetberry.done_line_1$
          - $daily-farming-level2-sweetberry.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openFarmingLevelMenu"
        close: true
items:
  level2BambooActiveFalse: $daily-farming-level2-bamboo.target_drops_slug$
  level2BambooActiveTrue: $daily-farming-level2-bamboo.target_drops_slug$ $enchants$ $flags$
  level2CactusActiveFalse: $daily-farming-level2-cactus.target_drops_slug$
  level2CactusActiveTrue: $daily-farming-level2-cactus.target_drops_slug$ $enchants$ $flags$
  level2MelonActiveFalse: $daily-farming-level2-melon.target_drops_slug$
  level2MelonActiveTrue: $daily-farming-level2-melon.target_drops_slug$ $enchants$ $flags$
  level2PumpkinActiveFalse: $daily-farming-level2-pumpkin.target_drops_slug$
  level2PumpkinActiveTrue: $daily-farming-level2-pumpkin.target_drops_slug$ $enchants$ $flags$
  level2SweetberryActiveFalse: $daily-farming-level2-sweetberry.target_drops_slug$
  level2SweetberryActiveTrue: $daily-farming-level2-sweetberry.target_drops_slug$ $enchants$ $flags$
