# package:
#   templates:
#     - dailyQuests

# objectives:
#   oak: "block OAK_LOG -16 conditions:isPlayerInMiningWorld events:oakShrine,addShrineTag1 notify"
#   oakShrine: "chestput $shrineCoords$ oaklogs:16 events:oakComplete,deleteShrineTag1 notify"
  
#   birch: "block BIRCH_LOG -16 conditions:isPlayerInMiningWorld events:birchShrine,addShrineTag2 notify"
#   birchShrine: "chestput $shrineCoords$ birchlogs:16 events:birchComplete,deleteShrineTag2 notify"

#   darkoak: "block DARK_OAK_LOG -16 conditions:isPlayerInMiningWorld events:darkoakShrine,addShrineTag3 notify"
#   darkoakShrine: "chestput $shrineCoords$ darkoaklogs:16 events:darkoakComplete,deleteShrineTag3 notify"
  
#   crimson: "block CRIMSON_STEM -16 conditions:isPlayerInNetherWorld events:crimsonShrine,addShrineTag4 notify"
#   crimsonShrine: "chestput $shrineCoords$ crimsonstem:16 events:crimsonComplete,deleteShrineTag4 notify"

#   spruce: "block SPRUCE_LOG -16 conditions:isPlayerInMiningWorld events:spruceShrine,addShrineTag5 notify"
#   spruceShrine: "chestput $shrineCoords$ sprucelogs:16 events:spruceComplete,deleteShrineTag5 notify"

  

# conditions:
#   shrineTag1: tag shrineTag1
#   shrineTag2: tag shrineTag2
#   shrineTag3: tag shrineTag3
#   shrineTag4: tag shrineTag4
#   shrineTag5: tag shrineTag5

#   isPlayerInMiningWorld: 'world $worldName$'
#   isPlayerInNetherWorld: 'world $worldNameNether$'
#   oakTaken: "tag oak_taken"
#   oakActive: "and oakTaken,!oakComplete"
#   oakComplete: "tag oak_complete"
  

#   birchTaken: "tag birch_taken"
#   birchActive: "and birchTaken,!birchComplete"
#   birchComplete: "tag birch_complete"
  

#   darkoakTaken: "tag darkoak_taken"
#   darkoakActive: "and darkoakTaken,!darkoakComplete"
#   darkoakComplete: "tag darkoak_complete"

  
#   crimsonTaken: "tag crimson_taken"
#   crimsonActive: "and crimsonTaken,!crimsonComplete"
#   crimsonComplete: "tag crimson_complete"

  
#   spruceTaken: "tag spruce_taken"
#   spruceActive: "and spruceTaken,!spruceComplete"
#   spruceComplete: "tag spruce_complete"

#   woodcuttingQuestAlreadyActive: or oakActive,birchActive,darkoakActive,crimsonActive,spruceActive
  
# events:
#   addShrineTag1: tag add shrineTag1
#   addShrineTag2: tag add shrineTag2
#   addShrineTag3: tag add shrineTag3
#   addShrineTag4: tag add shrineTag4
#   addShrineTag5: tag add shrineTag5

#   deleteShrineTag1: tag delete shrineTag1
#   deleteShrineTag2: tag delete shrineTag2
#   deleteShrineTag3: tag delete shrineTag3
#   deleteShrineTag4: tag delete shrineTag4
#   deleteShrineTag5: tag delete shrineTag5
#   ################
#   ## Objectives ##
#   ################
#   giveoakObjective: "objective add oak"
#   giveoakShrineObjective: "objective add oakShrine"
  
#   givebirchQuest: "objective add birch"
#   givebirchShrineObjective: "objective add birchShrine"

#   givedarkoakQuest: "objective add darkoak"
#   givedarkoakShrineObjective: "objective add darkoakShrine"

#   givecrimsonQuest: "objective add crimson"
#   givecrimsonShrineObjective: "objective add crimsonShrine"
  
#   givespruceQuest: "objective add spruce"
#   givespruceShrineObjective: "objective add spruceShrine"
  
#   ##########
#   ## TAGS ##
#   ##########
#   addoakTakenTag: "tag add oak_taken"
#   addoakCompleteTag: "tag add oak_complete"
  
#   addbirchTakenTag: "tag add birch_taken"
#   addbirchCompleteTag: "tag add birch_complete"
  
#   adddarkoakTakenTag: "tag add darkoak_taken"
#   adddarkoakCompleteTag: "tag add darkoak_complete"
  
#   addcrimsonTakenTag: "tag add crimson_taken"
#   addcrimsonCompleteTag: "tag add crimson_complete"
  
#   addspruceTakenTag: "tag add spruce_taken"
#   addspruceCompleteTag: "tag add spruce_complete"
  
#   ###################
#   ## NOTIFICATIONS ##
#   ###################
#   oakStartNotice: "notify &aQuest started: &bOak Wood io:subtitle"
#   oakShrineNotice: "notify &aObjective: &bPlace 16 oak logs in the shrine io:subtitle"

#   birchStartNotice: "notify &aQuest started: &6Birch Wood io:subtitle"
#   birchShrineNotice: "notify &aObjective: &bPlace 16 birch logs in the shrine io:subtitle"

#   darkoakStartNotice: "notify &aQuest started: &fDarkoak Wood io:subtitle"
#   darkoakShrineNotice: "notify &aObjective: &bPlace 16 darkoak logs in the shrine io:subtitle"

#   crimsonStartNotice: "notify &aQuest started: &cCrimson Wood io:subtitle"
#   crimsonShrineNotice: "notify &aObjective: &bPlace 16 crimson stem in the shrine io:subtitle"

#   spruceStartNotice: "notify &aQuest started: &dSpruce Wood io:subtitle"
#   spruceShrineNotice: "notify &aObjective: &bPlace 16 spruce logs in the shrine io:subtitle"

#   woodcuttingQuestAlreadyActive: notify &4You already have an active quest in this category! io:subtitle conditions:woodcuttingQuestAlreadyActive
  
#   #############
#   ## Rewards ##
#   #############
#   oakReward: 'command eco give %player% 20'
#   birchReward: 'command eco give %player% 20'
#   darkoakReward: 'command eco give %player% 20'
#   crimsonReward: 'command eco give %player% 20'
#   spruceReward: 'command eco give %player% 20'
  
#   ############
#   ## Resets ##
#   ############
#   resetNotify: "notify \n&4You've resetted the quest! io:title"

#   resetoakTags: "tag delete oak_taken,oak_complete,shrineTag1"
#   resetoakObjective: "objective remove oak"
#   resetoakShrineObjective: "objective remove oakShrine"
  
#   resetbirchTags: "tag delete birch_taken,birch_complete,shrineTag2"
#   resetbirchObjective: "objective remove birch"
#   resetbirchShrineObjective: "objective remove birchShrine"
  
#   resetdarkoakTags: "tag delete darkoak_taken,darkoak_complete,shrineTag3"
#   resetdarkoakObjective: "objective remove darkoak"
#   resetdarkoakShrineObjective: "objective remove darkoakShrine"
  
#   resetcrimsonTags: "tag delete crimson_taken,crimson_complete,shrineTag4"
#   resetcrimsonObjective: "objective remove crimson"
#   resetcrimsonShrineObjective: "objective remove crimsonShrine"
  
#   resetspruceTags: "tag delete spruce_taken,spruce_complete,shrineTag5"
#   resetspruceObjective: "objective remove spruce"
#   resetspruceShrineObjective: "objective remove spruceShrine"
 
#   #############
#   ## Folders ##
#   #############
#   oakStart: "folder giveoakObjective,oakStartNotice,addoakTakenTag conditions:!woodcuttingQuestAlreadyActive"
#   oakShrine: "folder giveoakShrineObjective,oakShrineNotice"
#   oakComplete: 'folder oakReward,addoakCompleteTag'
#   oakReset: "folder resetoakTags,resetoakObjective,resetoakShrineObjective"
  
#   birchStart: "folder givebirchQuest,birchStartNotice,addbirchTakenTag conditions:!woodcuttingQuestAlreadyActive"
#   birchShrine: "folder givebirchShrineObjective,birchShrineNotice"
#   birchComplete: 'folder birchReward,addbirchCompleteTag'
#   birchReset: "folder resetbirchTags,resetbirchObjective"
  
#   darkoakStart: "folder givedarkoakQuest,darkoakStartNotice,adddarkoakTakenTag conditions:!woodcuttingQuestAlreadyActive"
#   darkoakShrine: "folder givedarkoakShrineObjective,darkoakShrineNotice"
#   darkoakComplete: 'folder darkoakReward,adddarkoakCompleteTag'
#   darkoakReset: "folder resetdarkoakTags,resetdarkoakObjective"
  
#   crimsonStart: "folder givecrimsonQuest,crimsonStartNotice,addcrimsonTakenTag conditions:!woodcuttingQuestAlreadyActive"
#   crimsonShrine: "folder givecrimsonShrineObjective,crimsonShrineNotice"
#   crimsonComplete: 'folder crimsonReward,addcrimsonCompleteTag'
#   crimsonReset: "folder resetcrimsonTags,resetcrimsonObjective"
  
#   spruceStart: "folder givespruceQuest,spruceStartNotice,addspruceTakenTag conditions:!woodcuttingQuestAlreadyActive"
#   spruceShrine: "folder givespruceShrineObjective,spruceShrineNotice"
#   spruceComplete: 'folder spruceReward,addspruceCompleteTag'
#   spruceReset: "folder resetspruceTags,resetspruceObjective"
# items:
#   oaklogs: "minecraft:oak_log"
#   birchlogs: minecraft:birch_log
#   darkoaklogs: minecraft:dark_oak_log
#   crimsonstem: minecraft:crimson_stem
#   sprucelogs: minecraft:spruce_log