package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 32
  reward_amount: 5000

  world: Mining
  world_display: Mining

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: iron ore
  target_upper: Iron ore
  
  target_drops: iron ingot
  target_drops_plural: iron ingots
  
  target_slug: iron_ore

## Due to limitations, slug value must match item key
  target_drops_slug: iron_ingot

items:
  iron_ingot: minecraft:$target_drops_slug$