package:
  templates:
    - daily-lumber

variables:

  objective_amount: 16
  reward_amount: 2750
  
  world: The_Ark_nether
  world_display: Nether

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: crimson stems
  target_upper: Crimson stems
  
  target_drops: crimson stem
  target_drops_plural: crimson stems
  
  target_slug: crimson_stem
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: crimson_stem
  
items:
  crimson_stem: minecraft:$target_drops_slug$