package:
  templates:
    - daily-lumber

variables:

  objective_amount: 16
  reward_amount: 2500
  
  world: Mining
  world_display: Mining

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: dark oak logs
  target_upper: Dark oak logs
  
  target_drops: dark oak log
  target_drops_plural: dark oak logs
  
  target_slug: dark_oak_log
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: dark_oak_log
  
items:
  dark_oak_log: minecraft:$target_drops_slug$