package:
  templates:
    - daily-template-lumber

variables:

  objective_amount: 16
  reward_amount: 2750
  
  world: Mining
  world_display: Mining

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: birch logs
  target_upper: Birch logs
  
  target_drops: birch log
  target_drops_plural: birch logs
  
  target_slug: birch_log
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: birch_log
  
items:
  birch_log: minecraft:$target_drops_slug$