package:
  templates:
  - daily
menus:
  miningQuestsMenu:
    height: 4
    title: Mining Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level2DiamondOreActiveFalse,level2DiamondOreActiveTrue,level2DiamondOreShrine,level2DiamondOreShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level2DiamondOreActiveFalse:
        item: level2DiamondOreActiveFalse
        conditions: "!daily-mining-level2-diamondOre.collectTaken"
        text:
          - $daily-mining-level2-diamondOre.title$
          - $daily-mining-level2-diamondOre.description_line_1$
          - $daily-mining-level2-diamondOre.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.miningCheckActive,daily-mining-level2-diamondOre.collectStartFolder
        close: true
      level2DiamondOreActiveTrue:
        item: level2DiamondOreActiveTrue
        conditions: daily-mining-level2-diamondOre.collectTaken,!daily-mining-level2-diamondOre.shrineTaken
        text:
          - $daily-mining-level2-diamondOre.title$
          - $daily-mining-level2-diamondOre.description_line_1$
          - $daily-mining-level2-diamondOre.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mining-level2-diamondOre.objective.collect.absoluteAmount%/%daily-mining-level2-diamondOre.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mining-level2-diamondOre.reset
        close: true
      level2DiamondOreShrine:
        item: level2DiamondOreActiveTrue
        conditions: daily-mining-level2-diamondOre.shrineTaskActive
        text:
          - $daily-mining-level2-diamondOre.title$
          - $daily-mining-level2-diamondOre.shrine_line_1$
          - $daily-mining-level2-diamondOre.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2DiamondOreShrineFinished:
        item: questComplete
        conditions: daily-mining-level2-diamondOre.questComplete
        text:
          - $daily-mining-level2-diamondOre.title$
          - $daily-mining-level2-diamondOre.done_line_1$
          - $daily-mining-level2-diamondOre.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openMiningLevelMenu"
        close: true
items:
  level2DiamondOreActiveFalse: $daily-mining-level2-diamondOre.target_drops_slug$
  level2DiamondOreActiveTrue: $daily-mining-level2-diamondOre.target_drops_slug$ $enchants$ $flags$
