package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 16
  reward_amount: 2500

  world: Mining
  world_display: Mining

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: gold ore
  target_upper: Gold ore
  
  target_drops: raw gold
  target_drops_plural: raw gold
  
  target_slug: gold_ore

## Due to limitations, slug value must match item key
  target_drops_slug: raw_gold

items:
  raw_gold: minecraft:$target_drops_slug$