events:
  startQuestWhisper: 'notify &e&oThe Oracle whispers to you... io:subtitle'
  resetNotify: "notify &4You've reset the quest! category:daily_task"
  
variables:

  ###################
  ## Context Based ##
  #################################################################################
  ## This section's variables must be called from a package consuming a template ##
  ## It is housed here in order to create a global format for all daily quests   ##
  #################################################################################
  title: '&b[$action_upper$ $target_upper$]'
  description_line_1: $action_upper$ &a&o$objective_amount$ &r&o$target$!
  description_line_2: In the &a&o$world_display$ &r&oworld.
  
  shrine_line_1: Bring &a&o$objective_amount$ &5&o$target_drops_plural$ to
  shrine_line_2: the &d&oshrine &5&oat spawn
  
  done_line_1: You $action_lower_past$ $objective_amount$ $target$!
  done_line_2: Do this quest again tomorrow!

  ################
  ## Conditions ##
  ################
  hasLevel2DailyExp: 'point daily.questexp 25'
  hasLevel3DailyExp: 'point daily.questexp 50'
  hasLevel4DailyExp: 'point daily.questexp 100'
  hasLevel5DailyExp: 'point daily.questexp 200'
  startQuestCheck: 'and !daily.$type_lower$Active'
  collectTaken: tag collect_taken
  collectComplete: tag collect_complete
  shrineTaken: tag shrine_taken
  shrineComplete: tag shrine_complete
  worldCheck: world $world$
  
  ########################
  ## Quest State checks ##
  ########################
  
  collectTaskActive: and collectTaken,!collectComplete
  shrineTaskActive: and collectComplete,!shrineComplete
  questComplete: and collectComplete,shrineComplete

  ##########
  ## Tags ##
  ##########
  
  addShrineTakenTag: tag add shrine_taken
  addShrineCompleteTag: tag add shrine_complete
  
  addCollectTakenTag: tag add collect_taken
  addCollectCompleteTag: tag add collect_complete

  ###############
  ## Objective ##
  ###############

  giveCollectObjective: objective add collect
  giveShrineObjective: objective add shrine

  ########
  ## IO ##
  ########

  collectWhisper: 'notify &e&o$action_upper$ &a&o$objective_amount$ &e&o$target$ from the &a&o$world_display$ &e&oworld... io:subtitle'
  collectStartNotice: 'notify &b&oObjective: &e&oThe Oracle asked you to \n&e&o$action_lower$ &a&o$objective_amount$ &e&o$target$ from the &a&o$world_display$ &e&oworld. category:daily_task'
  
  shrineWhisper: 'notify &e&oPlace &a&o$objective_amount$ &e&o$target$ in the &d&oshrine &e&oat spawn... io:subtitle'
  shrineStartNotice: 'notify &b&oObjective: &e&oThe Oracle asked you to \n&e&oplace &a&o$objective_amount$ &e&o$target$ in the &d&oshrine &e&oat spawn. category:daily_task'
  
  finishWhisper: 'notify &e&oThe Oracle acknowledges your dedication... io:subtitle'
  finishNotice: 'notify &2Your daily quests reward\:\n+ $$reward_amount$ category:daily_task'

  #############
  ## FOLDERS ##
  #############

  collectStartFolder: 'if startQuestCheck passStartFolderCheck else failStartFolderCheck'

  passStartFolderCheck: folder collectInitFolder,collectWhisper,collectStartNotice period:3
  failStartFolderCheck: notify &4You do not have enough quest points to start another quest!

  collectInitFolder: 'folder addCollectTakenTag,daily.add$type_upper$ActiveTag,giveCollectObjective,startQuestWhisper'
  
  shrineInitFolder: 'folder addCollectCompleteTag,addShrineTakenTag,giveShrineObjective,shrineWhisper'
  shrineStartFolder: 'folder shrineInitFolder,shrineStartNotice period:3'
  
  finishInitFolder: 'folder daily.delete$type_upper$ActiveTag,addShrineCompleteTag,finishWhisper'
  finishFolder: 'folder finishInitFolder,finishNotice,reward period:3'
  reset: 'folder resetCollectTags,resetObjectives,resetActive'
    
  reward: "command eco give %player% $reward_amount$"
  resetCollectTags: tag delete collect_taken,collect_complete,shrine_taken,shrine_complete
  resetObjectives: objective remove collect,shrine
  resetActive: tag delete daily.$type_lower$_active

  #######################
  ## End Context Based ##
  ###############################################################################

  status:
    notStarted: '&8&oStatus: &a&oNot Started'
    inProgress: '&8&oStatus: &6&oIn Progress!'
    complete: '&8&oStatus: &a&oComplete!'
  action:
    reset: '&7Right-click to reset'
    start: '&7Left-click to start'

  shrineLocation: 0;65;-2;Mining
  
  level1GUIItem: 'COPPER_INGOT'
  level2GUIItem: 'IRON_INGOT'
  level3GUIItem: 'GOLD_INGOT'
  level4GUIItem: 'DIAMOND'
  level5GUIItem: 'NETHERITE_INGOT'
  enchants: 'enchants:damage_all:1'  
  flags: 'flags:HIDE_ENCHANTS,HIDE_ATTRIBUTES'
  
notifications:
  daily_task:
   io: chat
   
items:
  questComplete: 'lime_concrete'
  filler: 'gray_stained_glass_pane'
  back: 'red_stained_glass_pane'