package:
  templates:
    - daily-template-farming
    
variables:

  objective_amount: 16
  reward_amount: 5000

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: pumpkin
  target_upper: Pumpkin
  
  target_drops: pumpkin
  target_drops_plural: pumpkin
  
  target_slug: pumpkin
  
  age: ''
  
  target_drops_slug: pumpkin
  
items:
  pumpkin: minecraft:$target_drops_slug$