package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 16
  reward_amount: 2750
  
  world: The_Ark_nether
  world_display: Nether

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: obsidian
  target_upper: Obsidian
  
  target_drops: obsidian
  target_drops_plural: obsidian
  
  target_slug: obsidian

## Due to limitations, slug value must match item key
  target_drops_slug: obsidian

items:
  obsidian: minecraft:$target_drops_slug$
