package:
  templates:
  - daily-template
menus:
  lumberQuestsMenu:
    height: 4
    title: Lumber Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level2BirchActiveFalse,level2BirchActiveTrue,level2BirchShrine,level2BirchShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level2BirchActiveFalse:
        item: level2BirchActiveFalse
        conditions: "!daily-lumber-level2-birch.collectTaken"
        text:
          - $daily-lumber-level2-birch.title$
          - $daily-lumber-level2-birch.description_line_1$
          - $daily-lumber-level2-birch.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.lumberCheckActive,daily-lumber-level2-birch.collectStartFolder
        close: true
      level2BirchActiveTrue:
        item: level2BirchActiveTrue
        conditions: daily-lumber-level2-birch.collectTaken,!daily-lumber-level2-birch.shrineTaken
        text:
          - $daily-lumber-level2-birch.title$
          - $daily-lumber-level2-birch.description_line_1$
          - $daily-lumber-level2-birch.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-level2-birch.objective.collect.absoluteAmount%/%daily-lumber-level2-birch.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-lumber-level2-birch.reset
        close: true
      level2BirchShrine:
        item: level2BirchActiveTrue
        conditions: daily-lumber-level2-birch.shrineTaskActive
        text:
          - $daily-lumber-level2-birch.title$
          - $daily-lumber-level2-birch.shrine_line_1$
          - $daily-lumber-level2-birch.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2BirchShrineFinished:
        item: questComplete
        conditions: daily-lumber-level2-birch.questComplete
        text:
          - $daily-lumber-level2-birch.title$
          - $daily-lumber-level2-birch.done_line_1$
          - $daily-lumber-level2-birch.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openLumberLevelMenu"
        close: true
items:
  level2BirchActiveFalse: $daily-lumber-level2-birch.target_drops_slug$
  level2BirchActiveTrue: $daily-lumber-level2-birch.target_drops_slug$ $enchants$ $flags$
