package:
  templates:
    - daily-lumber

variables:

  objective_amount: 16
  reward_amount: 2500
  
  world: Mining
  world_display: Mining

  action_upper: Chop
  action_lower: chop
  action_lower_past: chopped
  
  target: spruce logs
  target_upper: Spruce logs
  
  target_drops: spruce log
  target_drops_plural: spruce logs
  
  target_slug: spruce_log
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: spruce_log
  
items:
  spruce_log: minecraft:$target_drops_slug$