package:
  templates:
    - daily-template-farming
    
variables:

  objective_amount: 16
  reward_amount: 2750

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: cactus
  target_upper: Cactus
  
  target_drops: cactus
  target_drops_plural: cactus
  
  target_slug: cactus
  
  age: ''

  target_drops_slug: cactus

items:
  cactus: minecraft:$target_drops_slug$