package:
  templates:
  - daily-template
menus:
  miningQuestsMenu:
    height: 4
    title: Mining Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level1DiamondOreActiveFalse,level1DiamondOreActiveTrue,level1DiamondOreShrine,level1DiamondOreShrineFinished
      10: level1GoldOreActiveFalse,level1GoldOreActiveTrue,level1GoldOreShrine,level1GoldOreShrineFinished
      11: level1IronOreActiveFalse,level1IronOreActiveTrue,level1IronOreShrine,level1IronOreShrineFinished
      12: level1ObsidianActiveFalse,level1ObsidianActiveTrue,level1ObsidianShrine,level1ObsidianShrineFinished
      13: level1QuartzOreActiveFalse,level1QuartzOreActiveTrue,level1QuartzOreShrine,level1QuartzOreShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1DiamondOreActiveFalse:
        item: level1DiamondOreActiveFalse
        conditions: "!daily-mining-level1-diamondOre.collectTaken"
        text:
          - $daily-mining-level1-diamondOre.title$
          - $daily-mining-level1-diamondOre.description_line_1$
          - $daily-mining-level1-diamondOre.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.miningCheckActive,daily-mining-level1-diamondOre.collectStartFolder
        close: true
      level1DiamondOreActiveTrue:
        item: level1DiamondOreActiveTrue
        conditions: daily-mining-level1-diamondOre.collectTaken,!daily-mining-level1-diamondOre.shrineTaken
        text:
          - $daily-mining-level1-diamondOre.title$
          - $daily-mining-level1-diamondOre.description_line_1$
          - $daily-mining-level1-diamondOre.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mining-level1-diamondOre.objective.collect.absoluteAmount%/%daily-mining-level1-diamondOre.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mining-level1-diamondOre.reset
        close: true
      level1DiamondOreShrine:
        item: level1DiamondOreActiveTrue
        conditions: daily-mining-level1-diamondOre.shrineTaskActive
        text:
          - $daily-mining-level1-diamondOre.title$
          - $daily-mining-level1-diamondOre.shrine_line_1$
          - $daily-mining-level1-diamondOre.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1DiamondOreShrineFinished:
        item: questComplete
        conditions: daily-mining-level1-diamondOre.questComplete
        text:
          - $daily-mining-level1-diamondOre.title$
          - $daily-mining-level1-diamondOre.done_line_1$
          - $daily-mining-level1-diamondOre.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1GoldOreActiveFalse:
        item: level1GoldOreActiveFalse
        conditions: "!daily-mining-level1-goldOre.collectTaken"
        text:
          - $daily-mining-level1-goldOre.title$
          - $daily-mining-level1-goldOre.description_line_1$
          - $daily-mining-level1-goldOre.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.miningCheckActive,daily-mining-level1-goldOre.collectStartFolder
        close: true
      level1GoldOreActiveTrue:
        item: level1GoldOreActiveTrue
        conditions: daily-mining-level1-goldOre.collectTaken,!daily-mining-level1-goldOre.shrineTaken
        text:
          - $daily-mining-level1-goldOre.title$
          - $daily-mining-level1-goldOre.description_line_1$
          - $daily-mining-level1-goldOre.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mining-level1-goldOre.objective.collect.absoluteAmount%/%daily-mining-level1-goldOre.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mining-level1-goldOre.reset
        close: true
      level1GoldOreShrine:
        item: level1GoldOreActiveTrue
        conditions: daily-mining-level1-goldOre.shrineTaskActive
        text:
          - $daily-mining-level1-goldOre.title$
          - $daily-mining-level1-goldOre.shrine_line_1$
          - $daily-mining-level1-goldOre.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1GoldOreShrineFinished:
        item: questComplete
        conditions: daily-mining-level1-goldOre.questComplete
        text:
          - $daily-mining-level1-goldOre.title$
          - $daily-mining-level1-goldOre.done_line_1$
          - $daily-mining-level1-goldOre.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1IronOreActiveFalse:
        item: level1IronOreActiveFalse
        conditions: "!daily-mining-level1-ironOre.collectTaken"
        text:
          - $daily-mining-level1-ironOre.title$
          - $daily-mining-level1-ironOre.description_line_1$
          - $daily-mining-level1-ironOre.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.miningCheckActive,daily-mining-level1-ironOre.collectStartFolder
        close: true
      level1IronOreActiveTrue:
        item: level1IronOreActiveTrue
        conditions: daily-mining-level1-ironOre.collectTaken,!daily-mining-level1-ironOre.shrineTaken
        text:
          - $daily-mining-level1-ironOre.title$
          - $daily-mining-level1-ironOre.description_line_1$
          - $daily-mining-level1-ironOre.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mining-level1-ironOre.objective.collect.absoluteAmount%/%daily-mining-level1-ironOre.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mining-level1-ironOre.reset
        close: true
      level1IronOreShrine:
        item: level1IronOreActiveTrue
        conditions: daily-mining-level1-ironOre.shrineTaskActive
        text:
          - $daily-mining-level1-ironOre.title$
          - $daily-mining-level1-ironOre.shrine_line_1$
          - $daily-mining-level1-ironOre.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1IronOreShrineFinished:
        item: questComplete
        conditions: daily-mining-level1-ironOre.questComplete
        text:
          - $daily-mining-level1-ironOre.title$
          - $daily-mining-level1-ironOre.done_line_1$
          - $daily-mining-level1-ironOre.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1ObsidianActiveFalse:
        item: level1ObsidianActiveFalse
        conditions: "!daily-mining-level1-obsidian.collectTaken"
        text:
          - $daily-mining-level1-obsidian.title$
          - $daily-mining-level1-obsidian.description_line_1$
          - $daily-mining-level1-obsidian.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.miningCheckActive,daily-mining-level1-obsidian.collectStartFolder
        close: true
      level1ObsidianActiveTrue:
        item: level1ObsidianActiveTrue
        conditions: daily-mining-level1-obsidian.collectTaken,!daily-mining-level1-obsidian.shrineTaken
        text:
          - $daily-mining-level1-obsidian.title$
          - $daily-mining-level1-obsidian.description_line_1$
          - $daily-mining-level1-obsidian.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mining-level1-obsidian.objective.collect.absoluteAmount%/%daily-mining-level1-obsidian.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mining-level1-obsidian.reset
        close: true
      level1ObsidianShrine:
        item: level1ObsidianActiveTrue
        conditions: daily-mining-level1-obsidian.shrineTaskActive
        text:
          - $daily-mining-level1-obsidian.title$
          - $daily-mining-level1-obsidian.shrine_line_1$
          - $daily-mining-level1-obsidian.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1ObsidianShrineFinished:
        item: questComplete
        conditions: daily-mining-level1-obsidian.questComplete
        text:
          - $daily-mining-level1-obsidian.title$
          - $daily-mining-level1-obsidian.done_line_1$
          - $daily-mining-level1-obsidian.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1QuartzOreActiveFalse:
        item: level1QuartzOreActiveFalse
        conditions: "!daily-mining-level1-quartzOre.collectTaken"
        text:
          - $daily-mining-level1-quartzOre.title$
          - $daily-mining-level1-quartzOre.description_line_1$
          - $daily-mining-level1-quartzOre.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.miningCheckActive,daily-mining-level1-quartzOre.collectStartFolder
        close: true
      level1QuartzOreActiveTrue:
        item: level1QuartzOreActiveTrue
        conditions: daily-mining-level1-quartzOre.collectTaken,!daily-mining-level1-quartzOre.shrineTaken
        text:
          - $daily-mining-level1-quartzOre.title$
          - $daily-mining-level1-quartzOre.description_line_1$
          - $daily-mining-level1-quartzOre.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-mining-level1-quartzOre.objective.collect.absoluteAmount%/%daily-mining-level1-quartzOre.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-mining-level1-quartzOre.reset
        close: true
      level1QuartzOreShrine:
        item: level1QuartzOreActiveTrue
        conditions: daily-mining-level1-quartzOre.shrineTaskActive
        text:
          - $daily-mining-level1-quartzOre.title$
          - $daily-mining-level1-quartzOre.shrine_line_1$
          - $daily-mining-level1-quartzOre.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1QuartzOreShrineFinished:
        item: questComplete
        conditions: daily-mining-level1-quartzOre.questComplete
        text:
          - $daily-mining-level1-quartzOre.title$
          - $daily-mining-level1-quartzOre.done_line_1$
          - $daily-mining-level1-quartzOre.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openMiningLevelMenu"
        close: true
items:
  level1DiamondOreActiveFalse: $daily-mining-level1-diamondOre.target_drops_slug$
  level1DiamondOreActiveTrue: $daily-mining-level1-diamondOre.target_drops_slug$ $enchants$ $flags$
  level1GoldOreActiveFalse: $daily-mining-level1-goldOre.target_drops_slug$
  level1GoldOreActiveTrue: $daily-mining-level1-goldOre.target_drops_slug$ $enchants$ $flags$
  level1IronOreActiveFalse: $daily-mining-level1-ironOre.target_drops_slug$
  level1IronOreActiveTrue: $daily-mining-level1-ironOre.target_drops_slug$ $enchants$ $flags$
  level1ObsidianActiveFalse: $daily-mining-level1-obsidian.target_drops_slug$
  level1ObsidianActiveTrue: $daily-mining-level1-obsidian.target_drops_slug$ $enchants$ $flags$
  level1QuartzOreActiveFalse: $daily-mining-level1-quartzOre.target_drops_slug$
  level1QuartzOreActiveTrue: $daily-mining-level1-quartzOre.target_drops_slug$ $enchants$ $flags$
