package:
  templates:
  - daily
menus:
  fishingQuestsMenu:
    height: 4
    title: Fishing Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level1CodActiveFalse,level1CodActiveTrue,level1CodShrine,level1CodShrineFinished
      10: level1PufferActiveFalse,level1PufferActiveTrue,level1PufferShrine,level1PufferShrineFinished
      11: level1SalmonActiveFalse,level1SalmonActiveTrue,level1SalmonShrine,level1SalmonShrineFinished
      12: level1ShellActiveFalse,level1ShellActiveTrue,level1ShellShrine,level1ShellShrineFinished
      13: level1TropicalActiveFalse,level1TropicalActiveTrue,level1TropicalShrine,level1TropicalShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1CodActiveFalse:
        item: level1CodActiveFalse
        conditions: "!daily-fishing-level1-cod.collectTaken"
        text:
          - $daily-fishing-level1-cod.title$
          - $daily-fishing-level1-cod.description_line_1$
          - $daily-fishing-level1-cod.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level1-cod.collectStartFolder
        close: true
      level1CodActiveTrue:
        item: level1CodActiveTrue
        conditions: daily-fishing-level1-cod.collectTaken,!daily-fishing-level1-cod.shrineTaken
        text:
          - $daily-fishing-level1-cod.title$
          - $daily-fishing-level1-cod.description_line_1$
          - $daily-fishing-level1-cod.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level1-cod.objective.collect.absoluteAmount%/%daily-fishing-level1-cod.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level1-cod.reset
        close: true
      level1CodShrine:
        item: level1CodActiveTrue
        conditions: daily-fishing-level1-cod.shrineTaskActive
        text:
          - $daily-fishing-level1-cod.title$
          - $daily-fishing-level1-cod.shrine_line_1$
          - $daily-fishing-level1-cod.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1CodShrineFinished:
        item: questComplete
        conditions: daily-fishing-level1-cod.questComplete
        text:
          - $daily-fishing-level1-cod.title$
          - $daily-fishing-level1-cod.done_line_1$
          - $daily-fishing-level1-cod.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1PufferActiveFalse:
        item: level1PufferActiveFalse
        conditions: "!daily-fishing-level1-puffer.collectTaken"
        text:
          - $daily-fishing-level1-puffer.title$
          - $daily-fishing-level1-puffer.description_line_1$
          - $daily-fishing-level1-puffer.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level1-puffer.collectStartFolder
        close: true
      level1PufferActiveTrue:
        item: level1PufferActiveTrue
        conditions: daily-fishing-level1-puffer.collectTaken,!daily-fishing-level1-puffer.shrineTaken
        text:
          - $daily-fishing-level1-puffer.title$
          - $daily-fishing-level1-puffer.description_line_1$
          - $daily-fishing-level1-puffer.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level1-puffer.objective.collect.absoluteAmount%/%daily-fishing-level1-puffer.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level1-puffer.reset
        close: true
      level1PufferShrine:
        item: level1PufferActiveTrue
        conditions: daily-fishing-level1-puffer.shrineTaskActive
        text:
          - $daily-fishing-level1-puffer.title$
          - $daily-fishing-level1-puffer.shrine_line_1$
          - $daily-fishing-level1-puffer.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1PufferShrineFinished:
        item: questComplete
        conditions: daily-fishing-level1-puffer.questComplete
        text:
          - $daily-fishing-level1-puffer.title$
          - $daily-fishing-level1-puffer.done_line_1$
          - $daily-fishing-level1-puffer.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1SalmonActiveFalse:
        item: level1SalmonActiveFalse
        conditions: "!daily-fishing-level1-salmon.collectTaken"
        text:
          - $daily-fishing-level1-salmon.title$
          - $daily-fishing-level1-salmon.description_line_1$
          - $daily-fishing-level1-salmon.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level1-salmon.collectStartFolder
        close: true
      level1SalmonActiveTrue:
        item: level1SalmonActiveTrue
        conditions: daily-fishing-level1-salmon.collectTaken,!daily-fishing-level1-salmon.shrineTaken
        text:
          - $daily-fishing-level1-salmon.title$
          - $daily-fishing-level1-salmon.description_line_1$
          - $daily-fishing-level1-salmon.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level1-salmon.objective.collect.absoluteAmount%/%daily-fishing-level1-salmon.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level1-salmon.reset
        close: true
      level1SalmonShrine:
        item: level1SalmonActiveTrue
        conditions: daily-fishing-level1-salmon.shrineTaskActive
        text:
          - $daily-fishing-level1-salmon.title$
          - $daily-fishing-level1-salmon.shrine_line_1$
          - $daily-fishing-level1-salmon.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1SalmonShrineFinished:
        item: questComplete
        conditions: daily-fishing-level1-salmon.questComplete
        text:
          - $daily-fishing-level1-salmon.title$
          - $daily-fishing-level1-salmon.done_line_1$
          - $daily-fishing-level1-salmon.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1ShellActiveFalse:
        item: level1ShellActiveFalse
        conditions: "!daily-fishing-level1-shell.collectTaken"
        text:
          - $daily-fishing-level1-shell.title$
          - $daily-fishing-level1-shell.description_line_1$
          - $daily-fishing-level1-shell.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level1-shell.collectStartFolder
        close: true
      level1ShellActiveTrue:
        item: level1ShellActiveTrue
        conditions: daily-fishing-level1-shell.collectTaken,!daily-fishing-level1-shell.shrineTaken
        text:
          - $daily-fishing-level1-shell.title$
          - $daily-fishing-level1-shell.description_line_1$
          - $daily-fishing-level1-shell.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level1-shell.objective.collect.absoluteAmount%/%daily-fishing-level1-shell.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level1-shell.reset
        close: true
      level1ShellShrine:
        item: level1ShellActiveTrue
        conditions: daily-fishing-level1-shell.shrineTaskActive
        text:
          - $daily-fishing-level1-shell.title$
          - $daily-fishing-level1-shell.shrine_line_1$
          - $daily-fishing-level1-shell.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1ShellShrineFinished:
        item: questComplete
        conditions: daily-fishing-level1-shell.questComplete
        text:
          - $daily-fishing-level1-shell.title$
          - $daily-fishing-level1-shell.done_line_1$
          - $daily-fishing-level1-shell.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1TropicalActiveFalse:
        item: level1TropicalActiveFalse
        conditions: "!daily-fishing-level1-tropical.collectTaken"
        text:
          - $daily-fishing-level1-tropical.title$
          - $daily-fishing-level1-tropical.description_line_1$
          - $daily-fishing-level1-tropical.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level1-tropical.collectStartFolder
        close: true
      level1TropicalActiveTrue:
        item: level1TropicalActiveTrue
        conditions: daily-fishing-level1-tropical.collectTaken,!daily-fishing-level1-tropical.shrineTaken
        text:
          - $daily-fishing-level1-tropical.title$
          - $daily-fishing-level1-tropical.description_line_1$
          - $daily-fishing-level1-tropical.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level1-tropical.objective.collect.absoluteAmount%/%daily-fishing-level1-tropical.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level1-tropical.reset
        close: true
      level1TropicalShrine:
        item: level1TropicalActiveTrue
        conditions: daily-fishing-level1-tropical.shrineTaskActive
        text:
          - $daily-fishing-level1-tropical.title$
          - $daily-fishing-level1-tropical.shrine_line_1$
          - $daily-fishing-level1-tropical.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1TropicalShrineFinished:
        item: questComplete
        conditions: daily-fishing-level1-tropical.questComplete
        text:
          - $daily-fishing-level1-tropical.title$
          - $daily-fishing-level1-tropical.done_line_1$
          - $daily-fishing-level1-tropical.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openFishingLevelMenu"
        close: true
items:
  level1CodActiveFalse: $daily-fishing-level1-cod.target_drops_slug$
  level1CodActiveTrue: $daily-fishing-level1-cod.target_drops_slug$ $enchants$ $flags$
  level1PufferActiveFalse: $daily-fishing-level1-puffer.target_drops_slug$
  level1PufferActiveTrue: $daily-fishing-level1-puffer.target_drops_slug$ $enchants$ $flags$
  level1SalmonActiveFalse: $daily-fishing-level1-salmon.target_drops_slug$
  level1SalmonActiveTrue: $daily-fishing-level1-salmon.target_drops_slug$ $enchants$ $flags$
  level1ShellActiveFalse: $daily-fishing-level1-shell.target_drops_slug$
  level1ShellActiveTrue: $daily-fishing-level1-shell.target_drops_slug$ $enchants$ $flags$
  level1TropicalActiveFalse: $daily-fishing-level1-tropical.target_drops_slug$
  level1TropicalActiveTrue: $daily-fishing-level1-tropical.target_drops_slug$ $enchants$ $flags$
