package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 32
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: copper ore
  target_upper: Copper ore
  
  target_drops: copper ingot
  target_drops_plural: copper ingots
  
  target_slug: copper_ore
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: copper_ingot
  
items:
  copper_ingot: minecraft:$target_drops_slug$