package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 16
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: copper ore
  target_upper: Copper ore
  
  target_drops: raw copper
  target_drops_plural: raw copper
  
  target_slug: copper_ore
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: raw_copper
  
items:
  raw_copper: minecraft:$target_drops_slug$