package:
  templates:
    - daily-template-fishing

variables:

  objective_amount: 2
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Fish
  action_lower: fish
  action_lower_past: caught
  
  target: tropical fish
  target_upper: Tropical Fish
  target_all_caps: TROPICAL_FISH
  
  target_drops: tropical fish
  target_drops_plural: tropical fish
  
  target_slug: tropical_fish
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: tropical_fish
  
items:
  tropical_fish: minecraft:$target_drops_slug$