package:
  templates:
  - daily-template
menus:
  questsMenu:
    height: 4
    title: Fishing Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: BoneActiveFalse,BoneActiveTrue,BoneShrine,BoneShrineFinished
      10: BookActiveFalse,BookActiveTrue,BookShrine,BookShrineFinished
      11: BootsActiveFalse,BootsActiveTrue,BootsShrine,BootsShrineFinished
      12: BottleActiveFalse,BottleActiveTrue,BottleShrine,BottleShrineFinished
      13: CodActiveFalse,CodActiveTrue,CodShrine,CodShrineFinished
      14: PufferActiveFalse,PufferActiveTrue,PufferShrine,PufferShrineFinished
      15: SaddleActiveFalse,SaddleActiveTrue,SaddleShrine,SaddleShrineFinished
      16: SalmonActiveFalse,SalmonActiveTrue,SalmonShrine,SalmonShrineFinished
      17: ShellActiveFalse,ShellActiveTrue,ShellShrine,ShellShrineFinished
      18: TropicalActiveFalse,TropicalActiveTrue,TropicalShrine,TropicalShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      BoneActiveFalse:
        item: BoneActiveFalse
        conditions: "!daily-fishing-bone.collectTaken"
        text:
          - $daily-fishing-bone.title$
          - $daily-fishing-bone.description_line_1$
          - $daily-fishing-bone.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-bone.collectStartFolder
        close: false
      BoneActiveTrue:
        item: BoneActiveTrue
        conditions: daily-fishing-bone.collectTaken,!daily-fishing-bone.shrineTaken
        text:
          - $daily-fishing-bone.title$
          - $daily-fishing-bone.description_line_1$
          - $daily-fishing-bone.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-bone.objective.collect.absoluteAmount%/%daily-fishing-bone.objective.collect.absoluteTotal%"
        close: false
      BoneShrine:
        item: BoneActiveTrue
        conditions: daily-fishing-bone.shrineTaskActive
        text:
          - $daily-fishing-bone.title$
          - $daily-fishing-bone.shrine_line_1$
          - $daily-fishing-bone.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      BoneShrineFinished:
        item: questComplete
        conditions: daily-fishing-bone.questComplete
        text:
          - $daily-fishing-bone.title$
          - $daily-fishing-bone.done_line_1$
          - $daily-fishing-bone.done_line_2$
          - 
          - $status.complete$
        close: false
      BookActiveFalse:
        item: BookActiveFalse
        conditions: "!daily-fishing-book.collectTaken"
        text:
          - $daily-fishing-book.title$
          - $daily-fishing-book.description_line_1$
          - $daily-fishing-book.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-book.collectStartFolder
        close: false
      BookActiveTrue:
        item: BookActiveTrue
        conditions: daily-fishing-book.collectTaken,!daily-fishing-book.shrineTaken
        text:
          - $daily-fishing-book.title$
          - $daily-fishing-book.description_line_1$
          - $daily-fishing-book.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-book.objective.collect.absoluteAmount%/%daily-fishing-book.objective.collect.absoluteTotal%"
        close: false
      BookShrine:
        item: BookActiveTrue
        conditions: daily-fishing-book.shrineTaskActive
        text:
          - $daily-fishing-book.title$
          - $daily-fishing-book.shrine_line_1$
          - $daily-fishing-book.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      BookShrineFinished:
        item: questComplete
        conditions: daily-fishing-book.questComplete
        text:
          - $daily-fishing-book.title$
          - $daily-fishing-book.done_line_1$
          - $daily-fishing-book.done_line_2$
          - 
          - $status.complete$
        close: false
      BootsActiveFalse:
        item: BootsActiveFalse
        conditions: "!daily-fishing-boots.collectTaken"
        text:
          - $daily-fishing-boots.title$
          - $daily-fishing-boots.description_line_1$
          - $daily-fishing-boots.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-boots.collectStartFolder
        close: false
      BootsActiveTrue:
        item: BootsActiveTrue
        conditions: daily-fishing-boots.collectTaken,!daily-fishing-boots.shrineTaken
        text:
          - $daily-fishing-boots.title$
          - $daily-fishing-boots.description_line_1$
          - $daily-fishing-boots.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-boots.objective.collect.absoluteAmount%/%daily-fishing-boots.objective.collect.absoluteTotal%"
        close: false
      BootsShrine:
        item: BootsActiveTrue
        conditions: daily-fishing-boots.shrineTaskActive
        text:
          - $daily-fishing-boots.title$
          - $daily-fishing-boots.shrine_line_1$
          - $daily-fishing-boots.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      BootsShrineFinished:
        item: questComplete
        conditions: daily-fishing-boots.questComplete
        text:
          - $daily-fishing-boots.title$
          - $daily-fishing-boots.done_line_1$
          - $daily-fishing-boots.done_line_2$
          - 
          - $status.complete$
        close: false
      BottleActiveFalse:
        item: BottleActiveFalse
        conditions: "!daily-fishing-bottle.collectTaken"
        text:
          - $daily-fishing-bottle.title$
          - $daily-fishing-bottle.description_line_1$
          - $daily-fishing-bottle.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-bottle.collectStartFolder
        close: false
      BottleActiveTrue:
        item: BottleActiveTrue
        conditions: daily-fishing-bottle.collectTaken,!daily-fishing-bottle.shrineTaken
        text:
          - $daily-fishing-bottle.title$
          - $daily-fishing-bottle.description_line_1$
          - $daily-fishing-bottle.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-bottle.objective.collect.absoluteAmount%/%daily-fishing-bottle.objective.collect.absoluteTotal%"
        close: false
      BottleShrine:
        item: BottleActiveTrue
        conditions: daily-fishing-bottle.shrineTaskActive
        text:
          - $daily-fishing-bottle.title$
          - $daily-fishing-bottle.shrine_line_1$
          - $daily-fishing-bottle.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      BottleShrineFinished:
        item: questComplete
        conditions: daily-fishing-bottle.questComplete
        text:
          - $daily-fishing-bottle.title$
          - $daily-fishing-bottle.done_line_1$
          - $daily-fishing-bottle.done_line_2$
          - 
          - $status.complete$
        close: false
      CodActiveFalse:
        item: CodActiveFalse
        conditions: "!daily-fishing-cod.collectTaken"
        text:
          - $daily-fishing-cod.title$
          - $daily-fishing-cod.description_line_1$
          - $daily-fishing-cod.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-cod.collectStartFolder
        close: false
      CodActiveTrue:
        item: CodActiveTrue
        conditions: daily-fishing-cod.collectTaken,!daily-fishing-cod.shrineTaken
        text:
          - $daily-fishing-cod.title$
          - $daily-fishing-cod.description_line_1$
          - $daily-fishing-cod.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-cod.objective.collect.absoluteAmount%/%daily-fishing-cod.objective.collect.absoluteTotal%"
        close: false
      CodShrine:
        item: CodActiveTrue
        conditions: daily-fishing-cod.shrineTaskActive
        text:
          - $daily-fishing-cod.title$
          - $daily-fishing-cod.shrine_line_1$
          - $daily-fishing-cod.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      CodShrineFinished:
        item: questComplete
        conditions: daily-fishing-cod.questComplete
        text:
          - $daily-fishing-cod.title$
          - $daily-fishing-cod.done_line_1$
          - $daily-fishing-cod.done_line_2$
          - 
          - $status.complete$
        close: false
      PufferActiveFalse:
        item: PufferActiveFalse
        conditions: "!daily-fishing-puffer.collectTaken"
        text:
          - $daily-fishing-puffer.title$
          - $daily-fishing-puffer.description_line_1$
          - $daily-fishing-puffer.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-puffer.collectStartFolder
        close: false
      PufferActiveTrue:
        item: PufferActiveTrue
        conditions: daily-fishing-puffer.collectTaken,!daily-fishing-puffer.shrineTaken
        text:
          - $daily-fishing-puffer.title$
          - $daily-fishing-puffer.description_line_1$
          - $daily-fishing-puffer.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-puffer.objective.collect.absoluteAmount%/%daily-fishing-puffer.objective.collect.absoluteTotal%"
        close: false
      PufferShrine:
        item: PufferActiveTrue
        conditions: daily-fishing-puffer.shrineTaskActive
        text:
          - $daily-fishing-puffer.title$
          - $daily-fishing-puffer.shrine_line_1$
          - $daily-fishing-puffer.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      PufferShrineFinished:
        item: questComplete
        conditions: daily-fishing-puffer.questComplete
        text:
          - $daily-fishing-puffer.title$
          - $daily-fishing-puffer.done_line_1$
          - $daily-fishing-puffer.done_line_2$
          - 
          - $status.complete$
        close: false
      SaddleActiveFalse:
        item: SaddleActiveFalse
        conditions: "!daily-fishing-saddle.collectTaken"
        text:
          - $daily-fishing-saddle.title$
          - $daily-fishing-saddle.description_line_1$
          - $daily-fishing-saddle.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-saddle.collectStartFolder
        close: false
      SaddleActiveTrue:
        item: SaddleActiveTrue
        conditions: daily-fishing-saddle.collectTaken,!daily-fishing-saddle.shrineTaken
        text:
          - $daily-fishing-saddle.title$
          - $daily-fishing-saddle.description_line_1$
          - $daily-fishing-saddle.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-saddle.objective.collect.absoluteAmount%/%daily-fishing-saddle.objective.collect.absoluteTotal%"
        close: false
      SaddleShrine:
        item: SaddleActiveTrue
        conditions: daily-fishing-saddle.shrineTaskActive
        text:
          - $daily-fishing-saddle.title$
          - $daily-fishing-saddle.shrine_line_1$
          - $daily-fishing-saddle.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      SaddleShrineFinished:
        item: questComplete
        conditions: daily-fishing-saddle.questComplete
        text:
          - $daily-fishing-saddle.title$
          - $daily-fishing-saddle.done_line_1$
          - $daily-fishing-saddle.done_line_2$
          - 
          - $status.complete$
        close: false
      SalmonActiveFalse:
        item: SalmonActiveFalse
        conditions: "!daily-fishing-salmon.collectTaken"
        text:
          - $daily-fishing-salmon.title$
          - $daily-fishing-salmon.description_line_1$
          - $daily-fishing-salmon.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-salmon.collectStartFolder
        close: false
      SalmonActiveTrue:
        item: SalmonActiveTrue
        conditions: daily-fishing-salmon.collectTaken,!daily-fishing-salmon.shrineTaken
        text:
          - $daily-fishing-salmon.title$
          - $daily-fishing-salmon.description_line_1$
          - $daily-fishing-salmon.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-salmon.objective.collect.absoluteAmount%/%daily-fishing-salmon.objective.collect.absoluteTotal%"
        close: false
      SalmonShrine:
        item: SalmonActiveTrue
        conditions: daily-fishing-salmon.shrineTaskActive
        text:
          - $daily-fishing-salmon.title$
          - $daily-fishing-salmon.shrine_line_1$
          - $daily-fishing-salmon.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      SalmonShrineFinished:
        item: questComplete
        conditions: daily-fishing-salmon.questComplete
        text:
          - $daily-fishing-salmon.title$
          - $daily-fishing-salmon.done_line_1$
          - $daily-fishing-salmon.done_line_2$
          - 
          - $status.complete$
        close: false
      ShellActiveFalse:
        item: ShellActiveFalse
        conditions: "!daily-fishing-shell.collectTaken"
        text:
          - $daily-fishing-shell.title$
          - $daily-fishing-shell.description_line_1$
          - $daily-fishing-shell.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-shell.collectStartFolder
        close: false
      ShellActiveTrue:
        item: ShellActiveTrue
        conditions: daily-fishing-shell.collectTaken,!daily-fishing-shell.shrineTaken
        text:
          - $daily-fishing-shell.title$
          - $daily-fishing-shell.description_line_1$
          - $daily-fishing-shell.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-shell.objective.collect.absoluteAmount%/%daily-fishing-shell.objective.collect.absoluteTotal%"
        close: false
      ShellShrine:
        item: ShellActiveTrue
        conditions: daily-fishing-shell.shrineTaskActive
        text:
          - $daily-fishing-shell.title$
          - $daily-fishing-shell.shrine_line_1$
          - $daily-fishing-shell.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      ShellShrineFinished:
        item: questComplete
        conditions: daily-fishing-shell.questComplete
        text:
          - $daily-fishing-shell.title$
          - $daily-fishing-shell.done_line_1$
          - $daily-fishing-shell.done_line_2$
          - 
          - $status.complete$
        close: false
      TropicalActiveFalse:
        item: TropicalActiveFalse
        conditions: "!daily-fishing-tropical.collectTaken"
        text:
          - $daily-fishing-tropical.title$
          - $daily-fishing-tropical.description_line_1$
          - $daily-fishing-tropical.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-fishing-tropical.collectStartFolder
        close: false
      TropicalActiveTrue:
        item: TropicalActiveTrue
        conditions: daily-fishing-tropical.collectTaken,!daily-fishing-tropical.shrineTaken
        text:
          - $daily-fishing-tropical.title$
          - $daily-fishing-tropical.description_line_1$
          - $daily-fishing-tropical.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-tropical.objective.collect.absoluteAmount%/%daily-fishing-tropical.objective.collect.absoluteTotal%"
        close: false
      TropicalShrine:
        item: TropicalActiveTrue
        conditions: daily-fishing-tropical.shrineTaskActive
        text:
          - $daily-fishing-tropical.title$
          - $daily-fishing-tropical.shrine_line_1$
          - $daily-fishing-tropical.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      TropicalShrineFinished:
        item: questComplete
        conditions: daily-fishing-tropical.questComplete
        text:
          - $daily-fishing-tropical.title$
          - $daily-fishing-tropical.done_line_1$
          - $daily-fishing-tropical.done_line_2$
          - 
          - $status.complete$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
items:
  BoneActiveFalse: $daily-fishing-bone.target_drops_slug$
  BoneActiveTrue: $daily-fishing-bone.target_drops_slug$ $enchants$ $flags$
  BookActiveFalse: $daily-fishing-book.target_drops_slug$
  BookActiveTrue: $daily-fishing-book.target_drops_slug$ $enchants$ $flags$
  BootsActiveFalse: $daily-fishing-boots.target_drops_slug$
  BootsActiveTrue: $daily-fishing-boots.target_drops_slug$ $enchants$ $flags$
  BottleActiveFalse: $daily-fishing-bottle.target_drops_slug$
  BottleActiveTrue: $daily-fishing-bottle.target_drops_slug$ $enchants$ $flags$
  CodActiveFalse: $daily-fishing-cod.target_drops_slug$
  CodActiveTrue: $daily-fishing-cod.target_drops_slug$ $enchants$ $flags$
  PufferActiveFalse: $daily-fishing-puffer.target_drops_slug$
  PufferActiveTrue: $daily-fishing-puffer.target_drops_slug$ $enchants$ $flags$
  SaddleActiveFalse: $daily-fishing-saddle.target_drops_slug$
  SaddleActiveTrue: $daily-fishing-saddle.target_drops_slug$ $enchants$ $flags$
  SalmonActiveFalse: $daily-fishing-salmon.target_drops_slug$
  SalmonActiveTrue: $daily-fishing-salmon.target_drops_slug$ $enchants$ $flags$
  ShellActiveFalse: $daily-fishing-shell.target_drops_slug$
  ShellActiveTrue: $daily-fishing-shell.target_drops_slug$ $enchants$ $flags$
  TropicalActiveFalse: $daily-fishing-tropical.target_drops_slug$
  TropicalActiveTrue: $daily-fishing-tropical.target_drops_slug$ $enchants$ $flags$
