package:
  templates:
    - daily

menus:
  levelMenu:
    height: 4
    title: Level Menu
    command: /levelfishing
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      "9": level1FishingQuestsMenu
      "10": level2FishingQuestsMenu
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1FishingQuestsMenu:
        item: level1FishingQuestsMenu
        text:
        - "&b[Level 1]"
        - "Fishing Quests"
        click:
          left: openLevel1FishingQuestsMenu
        close: true
      level2FishingQuestsMenu:
        item: level1FishingQuestsMenu
        text:
        - "&b[Level 2]"
        - "Fishing Quests"
        click:
          left: openLevel2FishingQuestsMenu
        close: true
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
events:
  openLevel1FishingQuestsMenu: menu open daily-fishing-level1.fishingQuestsMenu
  openLevel2FishingQuestsMenu: menu open daily-fishing-level2.fishingQuestsMenu

items:
  level1FishingQuestsMenu: "FISHING_ROD"
  level2FishingQuestsMenu: "FISHING_ROD"