package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 16
  reward_amount: 2500
  
  world: The_Ark_nether
  world_display: Nether

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: quartz ore
  target_upper: Quartz ore
  
  target_drops: quartz
  target_drops_plural: raw iron
  
  target_slug: nether_quartz_ore

## Due to limitations, slug value must match item key
  target_drops_slug: quartz

items:
  quartz: minecraft:$target_drops_slug$
