package:
  templates:
    - daily-base

objectives:
  collect: 'block $target_slug$ -$objective_amount$ conditions:worldCheck events:shrineStartFolder notify'
  shrine: 'chestput $shrineLocation$ $target_drops_slug$:$objective_amount$ events:finishFolder notify'

variables:
  type_upper: Mining
  type_lower: mining
  