package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 16
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: husks
  target_upper: Husks
  target_all_caps: HUSK
  
  target_drops: rotten flesh
  target_drops_plural: rotten flesh
  
  target_slug: zombie
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: rotten_flesh
  
items:
  rotten_flesh: minecraft:$target_drops_slug$