package:
  templates:
  - daily-template
menus:
  questsMenu:
    height: 4
    title: Lumber  Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: AcaciaActiveFalse,AcaciaActiveTrue,AcaciaShrine,AcaciaShrineFinished
      10: BirchActiveFalse,BirchActiveTrue,BirchShrine,BirchShrineFinished
      11: CherryActiveFalse,CherryActiveTrue,CherryShrine,CherryShrineFinished
      12: CrimsonActiveFalse,CrimsonActiveTrue,CrimsonShrine,CrimsonShrineFinished
      13: DarkoakActiveFalse,DarkoakActiveTrue,DarkoakShrine,DarkoakShrineFinished
      14: JungleActiveFalse,JungleActiveTrue,JungleShrine,JungleShrineFinished
      15: MangroveActiveFalse,MangroveActiveTrue,MangroveShrine,MangroveShrineFinished
      16: OakActiveFalse,OakActiveTrue,OakShrine,OakShrineFinished
      17: SpruceActiveFalse,SpruceActiveTrue,SpruceShrine,SpruceShrineFinished
      18: WarpedActiveFalse,WarpedActiveTrue,WarpedShrine,WarpedShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      AcaciaActiveFalse:
        item: AcaciaActiveFalse
        conditions: "!daily-lumber-acacia.collectTaken"
        text:
          - $daily-lumber-acacia.title$
          - $daily-lumber-acacia.description_line_1$
          - $daily-lumber-acacia.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-acacia.collectStartFolder
        close: false
      AcaciaActiveTrue:
        item: AcaciaActiveTrue
        conditions: daily-lumber-acacia.collectTaken,!daily-lumber-acacia.shrineTaken
        text:
          - $daily-lumber-acacia.title$
          - $daily-lumber-acacia.description_line_1$
          - $daily-lumber-acacia.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-acacia.objective.collect.absoluteAmount%/%daily-lumber-acacia.objective.collect.absoluteTotal%"
        close: false
      AcaciaShrine:
        item: AcaciaActiveTrue
        conditions: daily-lumber-acacia.shrineTaskActive
        text:
          - $daily-lumber-acacia.title$
          - $daily-lumber-acacia.shrine_line_1$
          - $daily-lumber-acacia.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      AcaciaShrineFinished:
        item: questComplete
        conditions: daily-lumber-acacia.questComplete
        text:
          - $daily-lumber-acacia.title$
          - $daily-lumber-acacia.done_line_1$
          - $daily-lumber-acacia.done_line_2$
          - 
          - $status.inProgress$
        close: false
      BirchActiveFalse:
        item: BirchActiveFalse
        conditions: "!daily-lumber-birch.collectTaken"
        text:
          - $daily-lumber-birch.title$
          - $daily-lumber-birch.description_line_1$
          - $daily-lumber-birch.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-birch.collectStartFolder
        close: false
      BirchActiveTrue:
        item: BirchActiveTrue
        conditions: daily-lumber-birch.collectTaken,!daily-lumber-birch.shrineTaken
        text:
          - $daily-lumber-birch.title$
          - $daily-lumber-birch.description_line_1$
          - $daily-lumber-birch.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-birch.objective.collect.absoluteAmount%/%daily-lumber-birch.objective.collect.absoluteTotal%"
        close: false
      BirchShrine:
        item: BirchActiveTrue
        conditions: daily-lumber-birch.shrineTaskActive
        text:
          - $daily-lumber-birch.title$
          - $daily-lumber-birch.shrine_line_1$
          - $daily-lumber-birch.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      BirchShrineFinished:
        item: questComplete
        conditions: daily-lumber-birch.questComplete
        text:
          - $daily-lumber-birch.title$
          - $daily-lumber-birch.done_line_1$
          - $daily-lumber-birch.done_line_2$
          - 
          - $status.inProgress$
        close: false
      CherryActiveFalse:
        item: CherryActiveFalse
        conditions: "!daily-lumber-cherry.collectTaken"
        text:
          - $daily-lumber-cherry.title$
          - $daily-lumber-cherry.description_line_1$
          - $daily-lumber-cherry.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-cherry.collectStartFolder
        close: false
      CherryActiveTrue:
        item: CherryActiveTrue
        conditions: daily-lumber-cherry.collectTaken,!daily-lumber-cherry.shrineTaken
        text:
          - $daily-lumber-cherry.title$
          - $daily-lumber-cherry.description_line_1$
          - $daily-lumber-cherry.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-cherry.objective.collect.absoluteAmount%/%daily-lumber-cherry.objective.collect.absoluteTotal%"
        close: false
      CherryShrine:
        item: CherryActiveTrue
        conditions: daily-lumber-cherry.shrineTaskActive
        text:
          - $daily-lumber-cherry.title$
          - $daily-lumber-cherry.shrine_line_1$
          - $daily-lumber-cherry.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      CherryShrineFinished:
        item: questComplete
        conditions: daily-lumber-cherry.questComplete
        text:
          - $daily-lumber-cherry.title$
          - $daily-lumber-cherry.done_line_1$
          - $daily-lumber-cherry.done_line_2$
          - 
          - $status.inProgress$
        close: false
      CrimsonActiveFalse:
        item: CrimsonActiveFalse
        conditions: "!daily-lumber-crimson.collectTaken"
        text:
          - $daily-lumber-crimson.title$
          - $daily-lumber-crimson.description_line_1$
          - $daily-lumber-crimson.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-crimson.collectStartFolder
        close: false
      CrimsonActiveTrue:
        item: CrimsonActiveTrue
        conditions: daily-lumber-crimson.collectTaken,!daily-lumber-crimson.shrineTaken
        text:
          - $daily-lumber-crimson.title$
          - $daily-lumber-crimson.description_line_1$
          - $daily-lumber-crimson.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-crimson.objective.collect.absoluteAmount%/%daily-lumber-crimson.objective.collect.absoluteTotal%"
        close: false
      CrimsonShrine:
        item: CrimsonActiveTrue
        conditions: daily-lumber-crimson.shrineTaskActive
        text:
          - $daily-lumber-crimson.title$
          - $daily-lumber-crimson.shrine_line_1$
          - $daily-lumber-crimson.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      CrimsonShrineFinished:
        item: questComplete
        conditions: daily-lumber-crimson.questComplete
        text:
          - $daily-lumber-crimson.title$
          - $daily-lumber-crimson.done_line_1$
          - $daily-lumber-crimson.done_line_2$
          - 
          - $status.inProgress$
        close: false
      DarkoakActiveFalse:
        item: DarkoakActiveFalse
        conditions: "!daily-lumber-darkoak.collectTaken"
        text:
          - $daily-lumber-darkoak.title$
          - $daily-lumber-darkoak.description_line_1$
          - $daily-lumber-darkoak.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-darkoak.collectStartFolder
        close: false
      DarkoakActiveTrue:
        item: DarkoakActiveTrue
        conditions: daily-lumber-darkoak.collectTaken,!daily-lumber-darkoak.shrineTaken
        text:
          - $daily-lumber-darkoak.title$
          - $daily-lumber-darkoak.description_line_1$
          - $daily-lumber-darkoak.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-darkoak.objective.collect.absoluteAmount%/%daily-lumber-darkoak.objective.collect.absoluteTotal%"
        close: false
      DarkoakShrine:
        item: DarkoakActiveTrue
        conditions: daily-lumber-darkoak.shrineTaskActive
        text:
          - $daily-lumber-darkoak.title$
          - $daily-lumber-darkoak.shrine_line_1$
          - $daily-lumber-darkoak.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      DarkoakShrineFinished:
        item: questComplete
        conditions: daily-lumber-darkoak.questComplete
        text:
          - $daily-lumber-darkoak.title$
          - $daily-lumber-darkoak.done_line_1$
          - $daily-lumber-darkoak.done_line_2$
          - 
          - $status.inProgress$
        close: false
      JungleActiveFalse:
        item: JungleActiveFalse
        conditions: "!daily-lumber-jungle.collectTaken"
        text:
          - $daily-lumber-jungle.title$
          - $daily-lumber-jungle.description_line_1$
          - $daily-lumber-jungle.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-jungle.collectStartFolder
        close: false
      JungleActiveTrue:
        item: JungleActiveTrue
        conditions: daily-lumber-jungle.collectTaken,!daily-lumber-jungle.shrineTaken
        text:
          - $daily-lumber-jungle.title$
          - $daily-lumber-jungle.description_line_1$
          - $daily-lumber-jungle.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-jungle.objective.collect.absoluteAmount%/%daily-lumber-jungle.objective.collect.absoluteTotal%"
        close: false
      JungleShrine:
        item: JungleActiveTrue
        conditions: daily-lumber-jungle.shrineTaskActive
        text:
          - $daily-lumber-jungle.title$
          - $daily-lumber-jungle.shrine_line_1$
          - $daily-lumber-jungle.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      JungleShrineFinished:
        item: questComplete
        conditions: daily-lumber-jungle.questComplete
        text:
          - $daily-lumber-jungle.title$
          - $daily-lumber-jungle.done_line_1$
          - $daily-lumber-jungle.done_line_2$
          - 
          - $status.inProgress$
        close: false
      MangroveActiveFalse:
        item: MangroveActiveFalse
        conditions: "!daily-lumber-mangrove.collectTaken"
        text:
          - $daily-lumber-mangrove.title$
          - $daily-lumber-mangrove.description_line_1$
          - $daily-lumber-mangrove.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-mangrove.collectStartFolder
        close: false
      MangroveActiveTrue:
        item: MangroveActiveTrue
        conditions: daily-lumber-mangrove.collectTaken,!daily-lumber-mangrove.shrineTaken
        text:
          - $daily-lumber-mangrove.title$
          - $daily-lumber-mangrove.description_line_1$
          - $daily-lumber-mangrove.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-mangrove.objective.collect.absoluteAmount%/%daily-lumber-mangrove.objective.collect.absoluteTotal%"
        close: false
      MangroveShrine:
        item: MangroveActiveTrue
        conditions: daily-lumber-mangrove.shrineTaskActive
        text:
          - $daily-lumber-mangrove.title$
          - $daily-lumber-mangrove.shrine_line_1$
          - $daily-lumber-mangrove.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      MangroveShrineFinished:
        item: questComplete
        conditions: daily-lumber-mangrove.questComplete
        text:
          - $daily-lumber-mangrove.title$
          - $daily-lumber-mangrove.done_line_1$
          - $daily-lumber-mangrove.done_line_2$
          - 
          - $status.inProgress$
        close: false
      OakActiveFalse:
        item: OakActiveFalse
        conditions: "!daily-lumber-oak.collectTaken"
        text:
          - $daily-lumber-oak.title$
          - $daily-lumber-oak.description_line_1$
          - $daily-lumber-oak.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-oak.collectStartFolder
        close: false
      OakActiveTrue:
        item: OakActiveTrue
        conditions: daily-lumber-oak.collectTaken,!daily-lumber-oak.shrineTaken
        text:
          - $daily-lumber-oak.title$
          - $daily-lumber-oak.description_line_1$
          - $daily-lumber-oak.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-oak.objective.collect.absoluteAmount%/%daily-lumber-oak.objective.collect.absoluteTotal%"
        close: false
      OakShrine:
        item: OakActiveTrue
        conditions: daily-lumber-oak.shrineTaskActive
        text:
          - $daily-lumber-oak.title$
          - $daily-lumber-oak.shrine_line_1$
          - $daily-lumber-oak.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      OakShrineFinished:
        item: questComplete
        conditions: daily-lumber-oak.questComplete
        text:
          - $daily-lumber-oak.title$
          - $daily-lumber-oak.done_line_1$
          - $daily-lumber-oak.done_line_2$
          - 
          - $status.inProgress$
        close: false
      SpruceActiveFalse:
        item: SpruceActiveFalse
        conditions: "!daily-lumber-spruce.collectTaken"
        text:
          - $daily-lumber-spruce.title$
          - $daily-lumber-spruce.description_line_1$
          - $daily-lumber-spruce.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-spruce.collectStartFolder
        close: false
      SpruceActiveTrue:
        item: SpruceActiveTrue
        conditions: daily-lumber-spruce.collectTaken,!daily-lumber-spruce.shrineTaken
        text:
          - $daily-lumber-spruce.title$
          - $daily-lumber-spruce.description_line_1$
          - $daily-lumber-spruce.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-spruce.objective.collect.absoluteAmount%/%daily-lumber-spruce.objective.collect.absoluteTotal%"
        close: false
      SpruceShrine:
        item: SpruceActiveTrue
        conditions: daily-lumber-spruce.shrineTaskActive
        text:
          - $daily-lumber-spruce.title$
          - $daily-lumber-spruce.shrine_line_1$
          - $daily-lumber-spruce.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      SpruceShrineFinished:
        item: questComplete
        conditions: daily-lumber-spruce.questComplete
        text:
          - $daily-lumber-spruce.title$
          - $daily-lumber-spruce.done_line_1$
          - $daily-lumber-spruce.done_line_2$
          - 
          - $status.inProgress$
        close: false
      WarpedActiveFalse:
        item: WarpedActiveFalse
        conditions: "!daily-lumber-warped.collectTaken"
        text:
          - $daily-lumber-warped.title$
          - $daily-lumber-warped.description_line_1$
          - $daily-lumber-warped.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily-lumber-warped.collectStartFolder
        close: false
      WarpedActiveTrue:
        item: WarpedActiveTrue
        conditions: daily-lumber-warped.collectTaken,!daily-lumber-warped.shrineTaken
        text:
          - $daily-lumber-warped.title$
          - $daily-lumber-warped.description_line_1$
          - $daily-lumber-warped.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-lumber-warped.objective.collect.absoluteAmount%/%daily-lumber-warped.objective.collect.absoluteTotal%"
        close: false
      WarpedShrine:
        item: WarpedActiveTrue
        conditions: daily-lumber-warped.shrineTaskActive
        text:
          - $daily-lumber-warped.title$
          - $daily-lumber-warped.shrine_line_1$
          - $daily-lumber-warped.shrine_line_2$
          - 
          - $status.inProgress$
        close: false
      WarpedShrineFinished:
        item: questComplete
        conditions: daily-lumber-warped.questComplete
        text:
          - $daily-lumber-warped.title$
          - $daily-lumber-warped.done_line_1$
          - $daily-lumber-warped.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
items:
  AcaciaActiveFalse: $daily-lumber-acacia.target_drops_slug$
  AcaciaActiveTrue: $daily-lumber-acacia.target_drops_slug$ $enchants$ $flags$
  BirchActiveFalse: $daily-lumber-birch.target_drops_slug$
  BirchActiveTrue: $daily-lumber-birch.target_drops_slug$ $enchants$ $flags$
  CherryActiveFalse: $daily-lumber-cherry.target_drops_slug$
  CherryActiveTrue: $daily-lumber-cherry.target_drops_slug$ $enchants$ $flags$
  CrimsonActiveFalse: $daily-lumber-crimson.target_drops_slug$
  CrimsonActiveTrue: $daily-lumber-crimson.target_drops_slug$ $enchants$ $flags$
  DarkoakActiveFalse: $daily-lumber-darkoak.target_drops_slug$
  DarkoakActiveTrue: $daily-lumber-darkoak.target_drops_slug$ $enchants$ $flags$
  JungleActiveFalse: $daily-lumber-jungle.target_drops_slug$
  JungleActiveTrue: $daily-lumber-jungle.target_drops_slug$ $enchants$ $flags$
  MangroveActiveFalse: $daily-lumber-mangrove.target_drops_slug$
  MangroveActiveTrue: $daily-lumber-mangrove.target_drops_slug$ $enchants$ $flags$
  OakActiveFalse: $daily-lumber-oak.target_drops_slug$
  OakActiveTrue: $daily-lumber-oak.target_drops_slug$ $enchants$ $flags$
  SpruceActiveFalse: $daily-lumber-spruce.target_drops_slug$
  SpruceActiveTrue: $daily-lumber-spruce.target_drops_slug$ $enchants$ $flags$
  WarpedActiveFalse: $daily-lumber-warped.target_drops_slug$
  WarpedActiveTrue: $daily-lumber-warped.target_drops_slug$ $enchants$ $flags$
