package:
  templates:
    - daily

menus:
  levelMenu:
    height: 4
    title: Level Menu
    command: /levellumber
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      "9": level1LumberQuestsMenu
      "10": level2LumberQuestsMenu
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1LumberQuestsMenu:
        item: level1LumberQuestsMenu
        text:
        - "&b[Level 1]"
        - "Lumber Quests"
        click:
          left: openLevel1LumberQuestsMenu
        close: true
      level2LumberQuestsMenu:
        item: level1LumberQuestsMenu
        text:
        - "&b[Level 2]"
        - "Lumber Quests"
        click:
          left: openLevel2LumberQuestsMenu
        close: true
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
events:
  openLevel1LumberQuestsMenu: menu open daily-lumber-level1.lumberQuestsMenu
  openLevel2LumberQuestsMenu: menu open daily-lumber-level2.lumberQuestsMenu

items:
  level1LumberQuestsMenu: "IRON_AXE"
  level2LumberQuestsMenu: "IRON_AXE"