package:
  templates:
    - daily-template-fishing

variables:

  objective_amount: 1
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Fish
  action_lower: fish
  action_lower_past: caught
  
  target: nautilus shell
  target_upper: Nautilus Shell
  target_all_caps: NAUTILUS_SHELL
  
  target_drops: nautilus shell
  target_drops_plural: nautilus shells
  
  target_slug: nautilus_shell
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: nautilus_shell
  
items:
  nautilus_shell: minecraft:$target_drops_slug$