package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 4
  reward_amount: 2500
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: pigs
  target_upper: Pigs
  target_all_caps: PIG
  
  target_drops: cooked porkchop
  target_drops_plural: cooked porkchop
  
  target_slug: pig
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: cooked_porkchop
  
items:
  cooked_porkchop: minecraft:$target_drops_slug$