package:
  templates:
    - daily-template-farming
    
variables:

  objective_amount: 32
  reward_amount: 5000

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: wheat
  target_upper: Wheat
  
  target_drops: wheat
  target_drops_plural: wheat
  
  target_slug: wheat
  
  age: '[age=7]'

  target_drops_slug: wheat

items:
  wheat: minecraft:$target_drops_slug$