package:
  templates:
    - daily-farming
    
variables:

  objective_amount: 16
  reward_amount: "2500"

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: netherwart
  target_upper: Netherwart
  
  target_drops: netherwart
  target_drops_plural: netherwart
  
  target_slug: nether_wart
  
  age: '[age=3]'
  
  target_drops_slug: nether_wart
  
items:
  netherwart: minecraft:$target_drops_slug$