package:
  templates:
    - daily-template-farming
    
variables:

  objective_amount: 16
  reward_amount: 2500

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: sugarcane
  target_upper: Sugarcane
  
  target_drops: sugarcane
  target_drops_plural: sugarcane
  
  target_slug: sugar_cane
  
  age: '[age=0]'
  
  target_drops_slug: sugar_cane
  
items:
  sugar_cane: minecraft:$target_drops_slug$