package:
  templates:
    - daily-template-farming
    
variables:

  objective_amount: 16
  reward_amount: 5000

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: sweet berries
  target_upper: Sweet berries
  
  target_drops: sweet_berries
  target_drops_plural: sweet_berries
  
  target_slug: sweet_berry_bush
  
  age: '[age=3]'
  
  target_drops_slug: sweet_berries
  
items:
  sweet_berries: minecraft:$target_drops_slug$