package:
  templates:
    - daily

objectives:
  collect: 'block $target_slug$$age$ -$objective_amount$ conditions:worldCheck events:shrineStartFolder notify'
  shrine: 'chestput $shrineLocation$ $target$:$objective_amount$ events:finishFolder notify'
  
conditions:
  
  ################
  ## Tag checks ##
  ################
  collectTaken: '$collectTaken$'
  collectComplete: '$collectComplete$'
  shrineTaken: '$shrineTaken$'
  shrineComplete: '$shrineComplete$'
  worldCheck: '$worldCheck$'
  
  ########################
  ## Quest State checks ##
  ########################
  
  collectTaskActive: '$collectTaskActive$'
  shrineTaskActive: '$shrineTaskActive$'
  questComplete: '$questComplete$'

events:

  ##########
  ## Tags ##
  ##########
  
  addShrineTakenTag: '$addShrineTakenTag$'
  addShrineCompleteTag: '$addShrineCompleteTag$'
  addCollectTakenTag: '$addCollectTakenTag$'
  addCollectCompleteTag: '$addCollectCompleteTag$'
  
  ###############
  ## Objective ##
  ###############
  
  giveCollectObjective: '$giveCollectObjective$'
  giveShrineObjective: '$giveShrineObjective$'
    
  ########
  ## IO ##
  ########
    
  collectWhisper: '$collectWhisper$'
  collectStartNotice: $collectStartNotice$
  
  shrineWhisper: '$shrineWhisper$'
  shrineStartNotice: '$shrineStartNotice$'
  
  finishWhisper: '$finishWhisper$'
  finishNotice: '$finishNotice$'

  #############
  ## FOLDERS ##
  #############

  collectInitFolder: 'folder addCollectTakenTag,daily.addFarmingActiveTag,giveCollectObjective,startQuestWhisper'
  collectStartFolder: 'folder collectInitFolder,collectWhisper,collectStartNotice conditions:!daily.farmingActive period:3'
  
  shrineInitFolder: 'folder addCollectCompleteTag,addShrineTakenTag,giveShrineObjective,shrineWhisper'
  shrineStartFolder: 'folder shrineInitFolder,shrineStartNotice period:3'
  
  finishInitFolder: 'folder daily.deleteFarmingActiveTag,addShrineCompleteTag,finishWhisper'
  finishFolder: 'folder finishInitFolder,finishNotice,reward period:3'
  reset: 'folder resetCollectTags,resetObjectives,resetFarmingActive'
    
  reward: "point bank.denarii $reward_amount$ action:add"
  resetCollectTags: tag delete collect_taken,collect_complete,shrine_taken,shrine_complete
  resetObjectives: objective remove collect,shrine
  resetFarmingActive: tag delete daily.farming_active
  