package:
  templates:
    - daily-base

objectives:
  collect: 'block $target_slug$$age$ -$objective_amount$ conditions:worldCheck events:shrineStartFolder notify'
  shrine: 'chestput $shrineLocation$ $target$:$objective_amount$ events:finishFolder notify'

variables:
  type_upper: Farming
  type_lower: farming
  