package:
  templates:
    - daily-template-farming
    
variables:

  objective_amount: 32
  reward_amount: 5000

  world: Mining
  world_display: Mining
  
  action_upper: Harvest
  action_lower: harvest
  action_lower_past: harvested

  target: melon
  target_upper: Melon
  
  target_drops: melon
  target_drops_plural: melon
  
  target_slug: melon
  
  age: ''
  
  target_drops_slug: melon
    
items:
  melon: minecraft:$target_drops_slug$