package:
  templates:
  - daily
menus:
  fishingQuestsMenu:
    height: 4
    title: Fishing level2 Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level2CodActiveFalse,level2CodActiveTrue,level2CodShrine,level2CodShrineFinished
      10: level2PufferActiveFalse,level2PufferActiveTrue,level2PufferShrine,level2PufferShrineFinished
      11: level2SalmonActiveFalse,level2SalmonActiveTrue,level2SalmonShrine,level2SalmonShrineFinished
      12: level2ShellActiveFalse,level2ShellActiveTrue,level2ShellShrine,level2ShellShrineFinished
      13: level2TropicalActiveFalse,level2TropicalActiveTrue,level2TropicalShrine,level2TropicalShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level2CodActiveFalse:
        item: level2CodActiveFalse
        conditions: "!daily-fishing-level2-cod.collectTaken"
        text:
          - $daily-fishing-level2-cod.title$
          - $daily-fishing-level2-cod.description_line_1$
          - $daily-fishing-level2-cod.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level2-cod.collectStartFolder
        close: true
      level2CodActiveTrue:
        item: level2CodActiveTrue
        conditions: daily-fishing-level2-cod.collectTaken,!daily-fishing-level2-cod.shrineTaken
        text:
          - $daily-fishing-level2-cod.title$
          - $daily-fishing-level2-cod.description_line_1$
          - $daily-fishing-level2-cod.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level2-cod.objective.collect.absoluteAmount%/%daily-fishing-level2-cod.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level2-cod.reset
        close: true
      level2CodShrine:
        item: level2CodActiveTrue
        conditions: daily-fishing-level2-cod.shrineTaskActive
        text:
          - $daily-fishing-level2-cod.title$
          - $daily-fishing-level2-cod.shrine_line_1$
          - $daily-fishing-level2-cod.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2CodShrineFinished:
        item: questComplete
        conditions: daily-fishing-level2-cod.questComplete
        text:
          - $daily-fishing-level2-cod.title$
          - $daily-fishing-level2-cod.done_line_1$
          - $daily-fishing-level2-cod.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2PufferActiveFalse:
        item: level2PufferActiveFalse
        conditions: "!daily-fishing-level2-puffer.collectTaken"
        text:
          - $daily-fishing-level2-puffer.title$
          - $daily-fishing-level2-puffer.description_line_1$
          - $daily-fishing-level2-puffer.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level2-puffer.collectStartFolder
        close: true
      level2PufferActiveTrue:
        item: level2PufferActiveTrue
        conditions: daily-fishing-level2-puffer.collectTaken,!daily-fishing-level2-puffer.shrineTaken
        text:
          - $daily-fishing-level2-puffer.title$
          - $daily-fishing-level2-puffer.description_line_1$
          - $daily-fishing-level2-puffer.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level2-puffer.objective.collect.absoluteAmount%/%daily-fishing-level2-puffer.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level2-puffer.reset
        close: true
      level2PufferShrine:
        item: level2PufferActiveTrue
        conditions: daily-fishing-level2-puffer.shrineTaskActive
        text:
          - $daily-fishing-level2-puffer.title$
          - $daily-fishing-level2-puffer.shrine_line_1$
          - $daily-fishing-level2-puffer.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2PufferShrineFinished:
        item: questComplete
        conditions: daily-fishing-level2-puffer.questComplete
        text:
          - $daily-fishing-level2-puffer.title$
          - $daily-fishing-level2-puffer.done_line_1$
          - $daily-fishing-level2-puffer.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2SalmonActiveFalse:
        item: level2SalmonActiveFalse
        conditions: "!daily-fishing-level2-salmon.collectTaken"
        text:
          - $daily-fishing-level2-salmon.title$
          - $daily-fishing-level2-salmon.description_line_1$
          - $daily-fishing-level2-salmon.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level2-salmon.collectStartFolder
        close: true
      level2SalmonActiveTrue:
        item: level2SalmonActiveTrue
        conditions: daily-fishing-level2-salmon.collectTaken,!daily-fishing-level2-salmon.shrineTaken
        text:
          - $daily-fishing-level2-salmon.title$
          - $daily-fishing-level2-salmon.description_line_1$
          - $daily-fishing-level2-salmon.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level2-salmon.objective.collect.absoluteAmount%/%daily-fishing-level2-salmon.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level2-salmon.reset
        close: true
      level2SalmonShrine:
        item: level2SalmonActiveTrue
        conditions: daily-fishing-level2-salmon.shrineTaskActive
        text:
          - $daily-fishing-level2-salmon.title$
          - $daily-fishing-level2-salmon.shrine_line_1$
          - $daily-fishing-level2-salmon.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2SalmonShrineFinished:
        item: questComplete
        conditions: daily-fishing-level2-salmon.questComplete
        text:
          - $daily-fishing-level2-salmon.title$
          - $daily-fishing-level2-salmon.done_line_1$
          - $daily-fishing-level2-salmon.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2ShellActiveFalse:
        item: level2ShellActiveFalse
        conditions: "!daily-fishing-level2-shell.collectTaken"
        text:
          - $daily-fishing-level2-shell.title$
          - $daily-fishing-level2-shell.description_line_1$
          - $daily-fishing-level2-shell.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level2-shell.collectStartFolder
        close: true
      level2ShellActiveTrue:
        item: level2ShellActiveTrue
        conditions: daily-fishing-level2-shell.collectTaken,!daily-fishing-level2-shell.shrineTaken
        text:
          - $daily-fishing-level2-shell.title$
          - $daily-fishing-level2-shell.description_line_1$
          - $daily-fishing-level2-shell.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level2-shell.objective.collect.absoluteAmount%/%daily-fishing-level2-shell.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level2-shell.reset
        close: true
      level2ShellShrine:
        item: level2ShellActiveTrue
        conditions: daily-fishing-level2-shell.shrineTaskActive
        text:
          - $daily-fishing-level2-shell.title$
          - $daily-fishing-level2-shell.shrine_line_1$
          - $daily-fishing-level2-shell.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2ShellShrineFinished:
        item: questComplete
        conditions: daily-fishing-level2-shell.questComplete
        text:
          - $daily-fishing-level2-shell.title$
          - $daily-fishing-level2-shell.done_line_1$
          - $daily-fishing-level2-shell.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level2TropicalActiveFalse:
        item: level2TropicalActiveFalse
        conditions: "!daily-fishing-level2-tropical.collectTaken"
        text:
          - $daily-fishing-level2-tropical.title$
          - $daily-fishing-level2-tropical.description_line_1$
          - $daily-fishing-level2-tropical.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.fishingCheckActive,daily-fishing-level2-tropical.collectStartFolder
        close: true
      level2TropicalActiveTrue:
        item: level2TropicalActiveTrue
        conditions: daily-fishing-level2-tropical.collectTaken,!daily-fishing-level2-tropical.shrineTaken
        text:
          - $daily-fishing-level2-tropical.title$
          - $daily-fishing-level2-tropical.description_line_1$
          - $daily-fishing-level2-tropical.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-fishing-level2-tropical.objective.collect.absoluteAmount%/%daily-fishing-level2-tropical.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-fishing-level2-tropical.reset
        close: true
      level2TropicalShrine:
        item: level2TropicalActiveTrue
        conditions: daily-fishing-level2-tropical.shrineTaskActive
        text:
          - $daily-fishing-level2-tropical.title$
          - $daily-fishing-level2-tropical.shrine_line_1$
          - $daily-fishing-level2-tropical.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level2TropicalShrineFinished:
        item: questComplete
        conditions: daily-fishing-level2-tropical.questComplete
        text:
          - $daily-fishing-level2-tropical.title$
          - $daily-fishing-level2-tropical.done_line_1$
          - $daily-fishing-level2-tropical.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openFishingLevelMenu"
        close: true
items:
  level2CodActiveFalse: $daily-fishing-level2-cod.target_drops_slug$
  level2CodActiveTrue: $daily-fishing-level2-cod.target_drops_slug$ $enchants$ $flags$
  level2PufferActiveFalse: $daily-fishing-level2-puffer.target_drops_slug$
  level2PufferActiveTrue: $daily-fishing-level2-puffer.target_drops_slug$ $enchants$ $flags$
  level2SalmonActiveFalse: $daily-fishing-level2-salmon.target_drops_slug$
  level2SalmonActiveTrue: $daily-fishing-level2-salmon.target_drops_slug$ $enchants$ $flags$
  level2ShellActiveFalse: $daily-fishing-level2-shell.target_drops_slug$
  level2ShellActiveTrue: $daily-fishing-level2-shell.target_drops_slug$ $enchants$ $flags$
  level2TropicalActiveFalse: $daily-fishing-level2-tropical.target_drops_slug$
  level2TropicalActiveTrue: $daily-fishing-level2-tropical.target_drops_slug$ $enchants$ $flags$
