package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 16
  reward_amount: 2500

  world: Mining
  world_display: Mining

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: lapis ore
  target_upper: Lapis ore
  
  target_drops: lapis
  target_drops_plural: lapis
  
  target_slug: lapis_ore

## Due to limitations, slug value must match item key
  target_drops_slug: lapis_lazuli

items:
  lapis_lazuli: minecraft:$target_drops_slug$