package:
  templates:
  - daily-template
menus:
  farmingQuestsMenu:
    height: 4
    title: Farming level1 Quests
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      9: level1BeetrootActiveFalse,level1BeetrootActiveTrue,level1BeetrootShrine,level1BeetrootShrineFinished
      10: level1CarrotActiveFalse,level1CarrotActiveTrue,level1CarrotShrine,level1CarrotShrineFinished
      11: level1NetherwartActiveFalse,level1NetherwartActiveTrue,level1NetherwartShrine,level1NetherwartShrineFinished
      12: level1PotatoActiveFalse,level1PotatoActiveTrue,level1PotatoShrine,level1PotatoShrineFinished
      13: level1WheatActiveFalse,level1WheatActiveTrue,level1WheatShrine,level1WheatShrineFinished
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1BeetrootActiveFalse:
        item: level1BeetrootActiveFalse
        conditions: "!daily-farming-level1-beetroot.collectTaken"
        text:
          - $daily-farming-level1-beetroot.title$
          - $daily-farming-level1-beetroot.description_line_1$
          - $daily-farming-level1-beetroot.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level1-beetroot.collectStartFolder
        close: true
      level1BeetrootActiveTrue:
        item: level1BeetrootActiveTrue
        conditions: daily-farming-level1-beetroot.collectTaken,!daily-farming-level1-beetroot.shrineTaken
        text:
          - $daily-farming-level1-beetroot.title$
          - $daily-farming-level1-beetroot.description_line_1$
          - $daily-farming-level1-beetroot.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level1-beetroot.objective.collect.absoluteAmount%/%daily-farming-level1-beetroot.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level1-beetroot.reset
        close: true
      level1BeetrootShrine:
        item: level1BeetrootActiveTrue
        conditions: daily-farming-level1-beetroot.shrineTaskActive
        text:
          - $daily-farming-level1-beetroot.title$
          - $daily-farming-level1-beetroot.shrine_line_1$
          - $daily-farming-level1-beetroot.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1BeetrootShrineFinished:
        item: questComplete
        conditions: daily-farming-level1-beetroot.questComplete
        text:
          - $daily-farming-level1-beetroot.title$
          - $daily-farming-level1-beetroot.done_line_1$
          - $daily-farming-level1-beetroot.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1CarrotActiveFalse:
        item: level1CarrotActiveFalse
        conditions: "!daily-farming-level1-carrot.collectTaken"
        text:
          - $daily-farming-level1-carrot.title$
          - $daily-farming-level1-carrot.description_line_1$
          - $daily-farming-level1-carrot.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level1-carrot.collectStartFolder
        close: true
      level1CarrotActiveTrue:
        item: level1CarrotActiveTrue
        conditions: daily-farming-level1-carrot.collectTaken,!daily-farming-level1-carrot.shrineTaken
        text:
          - $daily-farming-level1-carrot.title$
          - $daily-farming-level1-carrot.description_line_1$
          - $daily-farming-level1-carrot.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level1-carrot.objective.collect.absoluteAmount%/%daily-farming-level1-carrot.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level1-carrot.reset
        close: true
      level1CarrotShrine:
        item: level1CarrotActiveTrue
        conditions: daily-farming-level1-carrot.shrineTaskActive
        text:
          - $daily-farming-level1-carrot.title$
          - $daily-farming-level1-carrot.shrine_line_1$
          - $daily-farming-level1-carrot.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1CarrotShrineFinished:
        item: questComplete
        conditions: daily-farming-level1-carrot.questComplete
        text:
          - $daily-farming-level1-carrot.title$
          - $daily-farming-level1-carrot.done_line_1$
          - $daily-farming-level1-carrot.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1NetherwartActiveFalse:
        item: level1NetherwartActiveFalse
        conditions: "!daily-farming-level1-netherwart.collectTaken"
        text:
          - $daily-farming-level1-netherwart.title$
          - $daily-farming-level1-netherwart.description_line_1$
          - $daily-farming-level1-netherwart.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level1-netherwart.collectStartFolder
        close: true
      level1NetherwartActiveTrue:
        item: level1NetherwartActiveTrue
        conditions: daily-farming-level1-netherwart.collectTaken,!daily-farming-level1-netherwart.shrineTaken
        text:
          - $daily-farming-level1-netherwart.title$
          - $daily-farming-level1-netherwart.description_line_1$
          - $daily-farming-level1-netherwart.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level1-netherwart.objective.collect.absoluteAmount%/%daily-farming-level1-netherwart.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level1-netherwart.reset
        close: true
      level1NetherwartShrine:
        item: level1NetherwartActiveTrue
        conditions: daily-farming-level1-netherwart.shrineTaskActive
        text:
          - $daily-farming-level1-netherwart.title$
          - $daily-farming-level1-netherwart.shrine_line_1$
          - $daily-farming-level1-netherwart.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1NetherwartShrineFinished:
        item: questComplete
        conditions: daily-farming-level1-netherwart.questComplete
        text:
          - $daily-farming-level1-netherwart.title$
          - $daily-farming-level1-netherwart.done_line_1$
          - $daily-farming-level1-netherwart.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1PotatoActiveFalse:
        item: level1PotatoActiveFalse
        conditions: "!daily-farming-level1-potato.collectTaken"
        text:
          - $daily-farming-level1-potato.title$
          - $daily-farming-level1-potato.description_line_1$
          - $daily-farming-level1-potato.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level1-potato.collectStartFolder
        close: true
      level1PotatoActiveTrue:
        item: level1PotatoActiveTrue
        conditions: daily-farming-level1-potato.collectTaken,!daily-farming-level1-potato.shrineTaken
        text:
          - $daily-farming-level1-potato.title$
          - $daily-farming-level1-potato.description_line_1$
          - $daily-farming-level1-potato.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level1-potato.objective.collect.absoluteAmount%/%daily-farming-level1-potato.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level1-potato.reset
        close: true
      level1PotatoShrine:
        item: level1PotatoActiveTrue
        conditions: daily-farming-level1-potato.shrineTaskActive
        text:
          - $daily-farming-level1-potato.title$
          - $daily-farming-level1-potato.shrine_line_1$
          - $daily-farming-level1-potato.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1PotatoShrineFinished:
        item: questComplete
        conditions: daily-farming-level1-potato.questComplete
        text:
          - $daily-farming-level1-potato.title$
          - $daily-farming-level1-potato.done_line_1$
          - $daily-farming-level1-potato.done_line_2$
          - 
          - $status.inProgress$
        close: false
      level1WheatActiveFalse:
        item: level1WheatActiveFalse
        conditions: "!daily-farming-level1-wheat.collectTaken"
        text:
          - $daily-farming-level1-wheat.title$
          - $daily-farming-level1-wheat.description_line_1$
          - $daily-farming-level1-wheat.description_line_2$
          - 
          - $status.notStarted$
          - $action.start$
        click:
          left: daily.farmingCheckActive,daily-farming-level1-wheat.collectStartFolder
        close: true
      level1WheatActiveTrue:
        item: level1WheatActiveTrue
        conditions: daily-farming-level1-wheat.collectTaken,!daily-farming-level1-wheat.shrineTaken
        text:
          - $daily-farming-level1-wheat.title$
          - $daily-farming-level1-wheat.description_line_1$
          - $daily-farming-level1-wheat.description_line_2$
          - 
          - $status.inProgress$
          - "%daily-farming-level1-wheat.objective.collect.absoluteAmount%/%daily-farming-level1-wheat.objective.collect.absoluteTotal%"
          - $action.reset$
        click:
          right: resetNotify,daily-farming-level1-wheat.reset
        close: true
      level1WheatShrine:
        item: level1WheatActiveTrue
        conditions: daily-farming-level1-wheat.shrineTaskActive
        text:
          - $daily-farming-level1-wheat.title$
          - $daily-farming-level1-wheat.shrine_line_1$
          - $daily-farming-level1-wheat.shrine_line_2$
          - 
          - $status.inProgress$
        close: true
      level1WheatShrineFinished:
        item: questComplete
        conditions: daily-farming-level1-wheat.questComplete
        text:
          - $daily-farming-level1-wheat.title$
          - $daily-farming-level1-wheat.done_line_1$
          - $daily-farming-level1-wheat.done_line_2$
          - 
          - $status.inProgress$
        close: false
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openFarmingLevelMenu"
        close: true
items:
  level1BeetrootActiveFalse: $daily-farming-level1-beetroot.target_drops_slug$
  level1BeetrootActiveTrue: $daily-farming-level1-beetroot.target_drops_slug$ $enchants$ $flags$
  level1CarrotActiveFalse: $daily-farming-level1-carrot.target_drops_slug$
  level1CarrotActiveTrue: $daily-farming-level1-carrot.target_drops_slug$ $enchants$ $flags$
  level1NetherwartActiveFalse: $daily-farming-level1-netherwart.target_drops_slug$
  level1NetherwartActiveTrue: $daily-farming-level1-netherwart.target_drops_slug$ $enchants$ $flags$
  level1PotatoActiveFalse: $daily-farming-level1-potato.target_drops_slug$
  level1PotatoActiveTrue: $daily-farming-level1-potato.target_drops_slug$ $enchants$ $flags$
  level1WheatActiveFalse: $daily-farming-level1-wheat.target_drops_slug$
  level1WheatActiveTrue: $daily-farming-level1-wheat.target_drops_slug$ $enchants$ $flags$
