package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 8
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: chicken
  target_upper: Chicken
  target_all_caps: CHICKEN
  
  target_drops: cooked chicken
  target_drops_plural: cooked chicken
  
  target_slug: pig
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: cooked_chicken
  
items:
  cooked_chicken: minecraft:$target_drops_slug$