package:
  templates:
    - daily

menus:
  levelMenu:
    height: 4
    title: Level Menu
    command: /levelmining
    slots:
      0-8: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      "9": level1MiningQuestsMenu
      "10": level2MiningQuestsMenu
      28-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"
      27: "back"
    items:
      level1MiningQuestsMenu:
        item: level1MiningQuestsMenu
        text:
        - "&b[Level 1]"
        - "Mining Quests"
        click:
          left: openLevel1MiningQuestsMenu
        close: true
      level2MiningQuestsMenu:
        item: level1MiningQuestsMenu
        text:
        - "&b[Level 2]"
        - "Mining Quests"
        click:
          left: openLevel2MiningQuestsMenu
        close: true
      filler:
        text: "&a "
        item: "filler"
      back:
        item: "back"
        text:
            - "&c&lGo Back"
        click:
          left: "daily.openDailyMenu"
        close: true
events:
  openLevel1MiningQuestsMenu: menu open daily-mining-level1.miningQuestsMenu
  openLevel2MiningQuestsMenu: menu open daily-mining-level2.miningQuestsMenu

items:
  level1MiningQuestsMenu: "IRON_PICKAXE"
  level2MiningQuestsMenu: "IRON_PICKAXE"