package:
  templates:
    - daily

menus:
  dailyMenu:
    height: 6
    title: '&f󏿽'
    command: /daily
    slots:
      '19': miningQuestsMenu
      '38': fishingQuestsMenu
      '22': mobkillingQuestsMenu
      '42': farmingQuestsMenu
      '25': lumberQuestsMenu
    items:
      miningQuestsMenu:
        item: miningQuestsMenu
        amount: 1
        text:
        - '&5[&dCategory&5]'
        - '&f&lMining Quests'
        - ''
        - '&d&oMiner?'
        - '&d&oI hardly know her!'
        click:
          left: openMiningLevelMenu
        close: false
      fishingQuestsMenu:
        item: fishingQuestsMenu
        amount: 1
        text:
        - '&5[&dCategory&5]'
        - '&f&lFishing Quests'
        - ''
        - '&d&oP. Sherman'
        - '&d&o42 Wallaby Way'
        click:
          left: openFishingLevelMenu
        close: false
      mobkillingQuestsMenu:
        item: mobkillingQuestsMenu
        amount: 1
        text:
        - '&5[&dCategory&5]'
        - '&f&lMob Quests'
        - ''
        - '&d&oMake the world'
        - '&d&oa better place,'
        - '&d&okill some mobs!'
        click:
          left: openMobkillLevelMenu
        close: false
      farmingQuestsMenu:
        item: farmingQuestsMenu
        amount: 1
        text:
        - '&5[&dCategory&5]'
        - '&f&lFarming Quests'
        - ''
        - '&d&oGrab a hoe!'
        - '&d&oPlow a field!'
        click:
          left: openFarmingLevelMenu
        close: false
      lumberQuestsMenu:
        item: lumberQuestsMenu
        amount: 1
        text:
        - '&5[&dCategory&5]'
        - '&f&lLumber Quests'
        - ''
        - '&d&oGrow a beard!'
        - '&d&oChop some wood!'
        click:
          left: openLumberLevelMenu
        close: false
conditions:

  farmingActive: tag farming_active
  miningActive: tag mining_active
  fishingActive: tag fishing_active
  mobkillActive: tag mobkill_active
  lumberActive: tag lumber_active

variables:
  activeQuestNotice: notify &4You already have an active quest in this category! category:daily_task

events:
  ##########
  ## Tags ##
  ##########

  addFarmingActiveTag: tag add farming_active
  deleteFarmingActiveTag: tag delete farming_active
  
  addMiningActiveTag: tag add mining_active
  deleteMiningActiveTag: tag delete mining_active
  
  addFishingActiveTag: tag add fishing_active
  deleteFishingActiveTag: tag delete fishing_active
  
  addMobkillActiveTag: tag add mobkill_active
  deleteMobkillActiveTag: tag delete mobkill_active
  
  addLumberActiveTag: tag add lumber_active
  deleteLumberActiveTag: tag delete lumber_active
  
  farmingCheckActive: $activeQuestNotice$ conditions:farmingActive
  miningCheckActive: $activeQuestNotice$ conditions:miningActive
  fishingCheckActive: $activeQuestNotice$ conditions:fishingActive
  mobkillCheckActive: $activeQuestNotice$ conditions:mobkillActive
  lumberCheckActive: $activeQuestNotice$ conditions:lumberActive

  resetCategoryTags: tag delete farming_active,mining_active,fishing_active,mobkill_active,lumber_active
  openMiningLevelMenu: menu open daily-mining.levelMenu
  openFishingLevelMenu: menu open daily-fishing.levelMenu
  openMobkillLevelMenu: menu open daily-mobkill.levelMenu
  openFarmingLevelMenu: menu open daily-farming.levelMenu
  openLumberLevelMenu: menu open daily-lumber.levelMenu
  menuOpenSound: notify &aOpening Quest Menu! sound:block.amethyst_block.chime
  menuCloseSound: notify &aClosing Quest Menu! sound:block.azalea.step
  openDailyMenu: menu open dailyMenu        

items:
  openMenuItem: BOOK title:Quests
  xpBottle: EXPERIENCE_BOTTLE
  filler: GRAY_STAINED_GLASS_PANE
  back: RED_STAINED_GLASS_PANE
  questComplete: LIME_CONCRETE
  
  # # Type Submenus
  miningQuestsMenu: IRON_PICKAXE $flags$
  fishingQuestsMenu: FISHING_ROD $flags$
  lumberQuestsMenu: IRON_AXE $flags$
  mobkillingQuestsMenu: IRON_SWORD $flags$
  farmingQuestsMenu: IRON_HOE $flags$