package:
  templates:
    - daily-template-mobkill

variables:

  objective_amount: 16
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Kill
  action_lower: kill
  action_lower_past: killed
  
  target: squid
  target_upper: Squid
  target_all_caps: SQUID
  
  target_drops: ink sac
  target_drops_plural: ink sacs
  
  target_slug: squid
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: ink_sac
  
items:
  ink_sac: minecraft:$target_drops_slug$