package:
  templates:
    - daily-template-mining

variables:

  objective_amount: 32
  reward_amount: 5000
  
  world: Mining
  world_display: Mining

  action_upper: Mine
  action_lower: mine
  action_lower_past: mined
  
  target: emerald ore
  target_upper: Emerald ore
  
  target_drops: emerald
  target_drops_plural: emeralds
  
  target_slug: emerald_ore
  
  ## Due to limitations, slug value must match item key
  target_drops_slug: emerald
  
items:
  emerald: minecraft:$target_drops_slug$